UNDEF C
UNDEF T
UNDEF M

ACCEPT C CHAR PROMPT 'Enter ERROR CODE ==> '
ACCEPT T CHAR PROMPT 'Enter TYPE E/O/I ==> '
ACCEPT M CHAR PROMPT 'Enter ERROR MSG  ==> '

INSERT INTO ERTB_MSGS
(ERR_CODE,LANGUAGE,MESSAGE,TYPE,CONFIRMATION_REQD,FUNCTION_ID,MAX_SUB_PARAM,MODIFIABLE,BATCH_TYPE,DERIVED_MSG, 
OVD_CLASS)
VALUES 
('&&C','ENG','&&M','&&T','N','',0,'Y','&&T','','N')
/

UNDEF C
UNDEF T
UNDEF M

