UNDEF FUNC
delete SMTB_MENU where function_id = '&&FUNC';

INSERT INTO SMTB_MENU
(CONTROL_STRING,HO_FUNCTION,FUNCTION_ID,EXECUTABLE_NAME,EXECUTABLE_TYPE,AVAILABLE,AEOD_AWARE,LOG_EVENT, 
CUST_ACCESS,MENU_HEAD,TYPE_STRING,MODULE,ALLOW_ONLY_IN_NORMAL,ALLOW_IN_DEMO,AUTO_AUTH,BRANCH_PROGRAM_ID)
VALUES 
('1111111111111111','N','&&FUNC','&&FUNC','F',1,1,1,0,'MODULE','M','&MODULE','Y',
'Y','Y',100)
/
delete SMTB_FUNCTION_DESCRIPTION where function_id = '&&FUNC';
INSERT INTO SMTB_FUNCTION_DESCRIPTION
(LANG_CODE,FUNCTION_ID,MAIN_MENU,SUB_MENU_1,SUB_MENU_2,BALOON_HELP,BRANCH_MODULE,BRANCH_PARENT_TASK)
VALUES 
('ENG','&&FUNC','&MAIN_MENU','&SUB_MENU_1','&SUB_MENU_2','','FC','0')
/
delete SMTB_ROLE_DETAIL where role_function = '&&FUNC' and role_id in ('MAINTENANCE');
INSERT INTO SMTB_ROLE_DETAIL
(ROLE_ID,ROLE_FUNCTION,CONTROL_STRING,CONTROL_1,CONTROL_10,CONTROL_11,CONTROL_12,CONTROL_13,CONTROL_14, 
CONTROL_15,CONTROL_16,CONTROL_2,CONTROL_3,CONTROL_4,CONTROL_5,CONTROL_6,CONTROL_7,CONTROL_8,CONTROL_9, 
AUTH_STAT,BRANCH_CODE)
VALUES 
('MAINTENANCE','&&FUNC','1111111111111111',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,'A','')
/
