SET VERIFY OFF

INSERT INTO SMTB_USER_ROLE
SELECT '&&ROLE_ID',
	'&&USER_ID',
	'A',
	A.BRANCH_CODE
FROM	STTM_BRANCH A
WHERE	NOT EXISTS
	(
	SELECT	1
	FROM	SMTB_USER_ROLE B
	WHERE	B.BRANCH_CODE = A.BRANCH_CODE
	AND	B.USER_ID = '&&USER_ID'
	AND	B.ROLE_ID = '&&ROLE_ID'
	)
AND	A.BRANCH_CODE = DECODE( UPPER('&&BRANCH_CODE'),'A',A.BRANCH_CODE,'ALL',A.BRANCH_CODE,
'&&BRANCH_CODE'
)
/

SELECT * FROM SMTB_USER_ROLE
WHERE USER_ID = '&&USER_ID'
/

SET VERIFY ON
UNDEF USER_ID ROLE_ID BRANCH_CODE
