-- CREATE OBJECTS THAT MAY HAVE BEEN MISSING
set verify off
UNDEF HOST_NAME
UNDEF TITLE_BAR_TEXT
UNDEF FLEXCUBE_USERNAME
UNDEF FLEXCUBE_PASSWORD
UNDEF FLEXML_SCHEMA
UNDEF FLEXML_PWD

ACCEPT HOST_NAME CHAR PROMPT          'Enter Connect String ==>       '
ACCEPT TITLE_BAR_TEXT CHAR PROMPT     'Enter TITLE BAR TEXT ==>       '
PROMPT



SET TRIMSPOOL ON PAGES 0 LINE 9999 FEED OFF
-- REMOVE ALL THE JOBS 
BEGIN
	FOR I IN
		(
		SELECT	JOB
		FROM	USER_JOBS
		) LOOP
BEGIN
	DBMS_JOB.REMOVE(I.JOB);
EXCEPTION
	WHEN OTHERS
	THEN
		DBMS_OUTPUT.PUT_LINE('ERR IN REMOVING JOB '||SQLERRM);
	END;
END LOOP;
END;
/

-- ENABLE TRIGGERS AND CONSTRAINTS

SPOOL TMP.TMP
SELECT DISTINCT 'ALTER TABLE '||TABLE_NAME||' ENABLE ALL TRIGGERS;'
FROM USER_TRIGGERS WHERE STATUS = 'DISABLED'
/
SELECT DISTINCT 'ALTER TABLE '||TABLE_NAME||' ENABLE CONSTRAINT '||CONSTRAINT_NAME||';'
FROM USER_CONSTRAINTS WHERE STATUS = 'DISABLED'
/
SPOOL OFF
SET FEED ON
@TMP.TMP

-- COMPILE INVALID SOURCE

SPOOL COMP.INV
PROMPT set feedback off
PROMPT spool tmp.tmp
PROMPT select 'ALTER '|| decode (object_type, 'PACKAGE BODY', 'PACKAGE',object_type)
PROMPT        || ' ' || object_name|| ' ' ||
PROMPT    decode (object_type, 'PACKAGE BODY', 'COMPILE BODY;','COMPILE;')
PROMPT from user_objects where  STATUS  = 'INVALID' order by  object_type
PROMPT /
PROMPT spool off
PROMPT set feedback on
PROMPT @tmp.tmp
SPOOL OFF

@COMP.INV
@COMP.INV
@COMP.INV


SPOOL TMP.TMP
REM
SPOOL OFF


set verify off


UPDATE STTM_BRANCH SET HOST_NAME = '&&HOST_NAME'
/
UPDATE STTM_CUSTOMER SET LIAB_NODE = '&&HOST_NAME'
/
UPDATE LMTB_OFFLINE_NODES SET NODE_NAME = '&&HOST_NAME'
/
UPDATE ICTB_ACC_ACTION SET NODE = '&&HOST_NAME'
/
UPDATE ICTB_ACTION_LOG SET NODE = '&&HOST_NAME'
/
UPDATE LMTB_OFFLINE_UTILS SET NODE_NAME = '&&HOST_NAME'
/
UPDATE MSTB_COMMSG_MASTER SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_CURRENT_MSG_IND_OUT SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_IN SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_IN_HIST SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_OUT SET NODE  = '&&HOST_NAME'
/
UPDATE MSTM_MCS SET NODE = '&&HOST_NAME'
/
UPDATE MSTM_UNDO set node = '&&HOST_NAME'
/
UPDATE STTM_UPLOAD_CUSTOMER SET LIAB_NODE = '&&HOST_NAME'
/
UPDATE CSTB_PARAM SET PARAM_VAL = '&WORK_AREA' WHERE PARAM_NAME = 'WORK_AREA'
/



