SELECT
'      "APPLICATION_DATE" is "'||GLOBAL.APPLICATION_DATE||'"
       "CONVERSION_DATE" is "'||GLOBAL.CONVERSION_DATE||'"
         "CONVERSION_GL" is "'||GLOBAL.CONVERSION_GL||'"
        "CONVERSION_RUN" is "'||GLOBAL.CONVERSION_RUN||'"
             "CONV_DATE" is "'||GLOBAL.CONV_DATE||'"
        "CURRENT_BRANCH" is "'||GLOBAL.CURRENT_BRANCH||'"
            "DTAG_PARAM" is "'||GLOBAL.DTAG_PARAM||'"
               "EUR_LCY" is "'||GLOBAL.EUR_LCY||'"
             "FUNC_TYPE" is "'||GLOBAL.FUNC_TYPE||'"
     "GET_NLS_DT_FORMAT" is "'||GLOBAL.GET_NLS_DT_FORMAT||'"
   "GET_PRODUCT_ACCRUAL" is "'||GLOBAL.GET_PRODUCT_ACCRUAL||'"
           "HEAD_OFFICE" is "'||GLOBAL.HEAD_OFFICE||'"
          "INTERFACE_ID" is "'||GLOBAL.INTERFACE_ID||'"
                  "LANG" is "'||GLOBAL.LANG||'"
                   "LCY" is "'||GLOBAL.LCY||'"
              "MAX_DATE" is "'||GLOBAL.MAX_DATE||'"
              "MIN_DATE" is "'||GLOBAL.MIN_DATE||'"
                  "NODE" is "'||GLOBAL.NODE||'"
         "ONLINE_GL_UPD" is "'||GLOBAL.ONLINE_GL_UPD||'"
                 "SLASH" is "'||GLOBAL.SLASH||'"
           "SPLIT_SETLS" is "'||GLOBAL.SPLIT_SETLS||'"
            "SWIFT_ADDR" is "'||GLOBAL.SWIFT_ADDR||'"
                   "TID" is "'||GLOBAL.TID||'"
                 "UDF15" is "'||GLOBAL.UDF15||'"
               "USER_ID" is "'||GLOBAL.USER_ID||'"
          "VDBAL_UPDATE" is "'||GLOBAL.VDBAL_UPDATE||'"
             "WORK_AREA" is "'||GLOBAL.WORK_AREA||'"
                   "X9$" is "'||GLOBAL.X9$||'"'
"          All Global Variables"
FROM DUAL
/
