SET TRIMSPOOL ON PAGES 0 LINE 999 FEED OFF
SPOOL ALTIND.TMP
SELECT 'ALTER INDEX '||INDEX_NAME||' REBUILD TABLESPACE FCCINDX;'
FROM USER_INDEXES
--WHERE TABLESPACE_NAME <> 'FCCINDX';
SPOOL OFF
set feed on
@ALTIND.TMP
