SET VERIFY OFF
SET FEED OFF
SET LINE 999
SET PAGES 0
SPOOL C:\CV\FUL.SQL
SELECT
DECODE
(
TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE,'DD-MM-YYYY'),1,2)),
(SELECT INSTR(HOLIDAY_LIST,'HH',1) FROM STTM_LCL_HOLIDAY WHERE MONTH =
TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE,'DD-MM-YYYY'),4,2))
AND YEAR =
TO_NUMBER(SUBSTR(TO_CHAR(SYSDATE,'DD-MM-YYYY'),7,4))
)
,'EXP FCCLIVE/FCCLIVE@FLEX FILE=f:\databackup\Live\fcc\CASA_FULLSCHEMA_'||TO_CHAR(SYSDATE,'MON')||'_'||TO_CHAR(SYSDATE,'DD-MM-YYYY')||'.DMP LOG = f:\databackup\Live\fcc\CASA_FULLSCHEMA_'||TO_CHAR(SYSDATE,'MON')||'_'||TO_CHAR(SYSDATE,'DD-MM-YYYY')||'.LOG FULL=Y
EXP FCIS/FCIS@FLEX FILE=f:\databackup\Live\fcis\IS_FULLSCHEMA_'||TO_CHAR(SYSDATE,'MON')||'_'||TO_CHAR(SYSDATE,'DD-MM-YYYY')||'.DMP LOG = f:\databackup\Live\fcc\IS_FULLSCHEMA_'||TO_CHAR(SYSDATE,'MON')||'_'||TO_CHAR(SYSDATE,'DD-MM-YYYY')||'.LOG FULL=Y'
,'REM')
FROM DUAL
/
SPOOL OFF
SET VERIFY ON
SET FEED ON
