SET VERIFY OFF FEED OFF HEAD OFF
UNDEF U
ACCEPT U CHAR PROMPT 'USER ID ==> '

UPDATE SMTB_USER
SET	AUTO_AUTH = DECODE(AUTO_AUTH,'Y','N','Y')
WHERE	USER_ID = '&&U'
/

SELECT 'AUTO AUTH FOR '||USER_ID||' IS SET TO '||AUTO_AUTH FROM SMTB_USER WHERE USER_ID = '&&U'
/

COMMIT
/

SET VERIFY ON FEED ON HEAD ON

