
accept CRN PROMPT 'Enter the contract reference no ==> '
set head on
set array 1
set linesize 10000
set pagesize 50000
set long 10000
set echo on
set colsep ";"
set trimspool on
SPOOL /tmp/BC_DETAILS.&CRN..SPL

PROMPT CSTB_CONTRACT
SELECT * FROM CSTB_CONTRACT WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CSTB_CONTRACT_EVENT_LOG
SELECT * FROM CSTB_CONTRACT_EVENT_LOG WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT BCTB_CONTRACT_MASTER
SELECT * FROM BCTB_CONTRACT_MASTER WHERE BCREFNO = UPPER('&CRN');

PROMPT BCTB_ACCRUAL_DETAILS
Select * from BCTB_ACCRUAL_DETAILS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_ACP_ADV_LOG
Select * from BCTB_ACP_ADV_LOG WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_AMOUNT_DUE
Select * from BCTB_AMOUNT_DUE WHERE BCREFNO = UPPER('&CRN');

PROMPT CSTBS_AMOUNT_DUE
select * from cstbs_amount_due where contract_ref_no =UPPER('&CRN');

select * from cstbs_amount_paid where contract_ref_no =UPPER('&CRN');

PROMPT BCTB_AUTOLIQ_DETAILS
Select * from BCTB_AUTOLIQ_DETAILS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_BASIS_AMTS_DUE
Select * from BCTB_BASIS_AMTS_DUE WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_ACC_EXC
Select * from BCTB_CONTRACT_ACC_EXC WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_ACC_FATE
Select * from BCTB_CONTRACT_ACC_FATE WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_DISC
Select * from BCTB_CONTRACT_DISC WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_DOCS
Select * from BCTB_CONTRACT_DOCS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_DOCS_CLAUSES
Select * from BCTB_CONTRACT_DOCS_CLAUSES WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_FFT
Select * from BCTB_CONTRACT_FFT WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_GOODS
Select * from BCTB_CONTRACT_GOODS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_INS
Select * from BCTB_CONTRACT_INS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_LIMITS
Select * from BCTB_CONTRACT_LIMITS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_PARTIES
Select * from BCTB_CONTRACT_PARTIES WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_PAY_EXC
Select * from BCTB_CONTRACT_PAY_EXC WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_PAY_FATE
Select * from BCTB_CONTRACT_PAY_FATE WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_RESERVE
Select * from BCTB_CONTRACT_RESERVE WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_SHIPMENT
Select * from BCTB_CONTRACT_SHIPMENT_INFO WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_BOE_TRACER
Select * from BCTB_CONTRACT_BOE_TRACER WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_BILL_ENTRY
SELECT * FROM BCTB_CONTRACT_BILL_ENTRY WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_STATUS_LOG
Select * from BCTB_CONTRACT_STATUS_LOG WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_ICCF_CALC
Select * from BCTB_ICCF_CALC WHERE BCREFNO = UPPER('&CRN');
PROMPT ISTBS_MSGHO
SELECT * FROM ISTBS_MSGHO WHERE CONTRACT_REF_NO = '&CRN';
PROMPT BCTB_ICCF_DETAILS
Select * from BCTB_ICCF_DETAILS WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_ICCF_MASTER
Select * from BCTB_ICCF_MASTER WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_PARTIES_ADDS
Select * from BCTB_PARTIES_ADDRESSES WHERE BCREFNO = UPPER('&CRN');
PROMPT BCTB_CONTRACT_CHANGE_LOG
Select * from BCTW_CONTRACT_CHANGE_LOG WHERE CONTRACT_REF_NO = UPPER('&CRN');
PROMPT ACVW_ALL_AC_ENTRIES
SELECT * FROM ACTB_DAILY_LOG WHERE TRN_REF_NO = UPPER('&CRN');
SELECT * FROM ACVW_ALL_AC_ENTRIES WHERE TRN_REF_NO = UPPER('&CRN');
PROMPT ACTB_DAILY_GHOST_LOG
select * from actb_daily_ghost_log where trn_ref_no = UPPER('&CRN');
PROMPT ISTBS_CONTRACTIS
SELECT * FROM ISTBS_CONTRACTIS WHERE CONTRACT_REF_NO = UPPER('&CRN');
PROMPT ISTBS_CONTRACT_DETAILS
SELECT * FROM ISTBS_CONTRACT_DETAILS WHERE CONTRACT_REF_NO = upper('&CRN');
PROMPT ISTBS_CONTRACTIS_SWIFT
SELECT * FROM ISTBS_CONTRACTIS_SWIFT WHERE CONTRACT_REF_NO = UPPER('&CRN');
PROMPT CFTBS_CONTRACT_CHARGES
SELECT * FROM CFTBS_CONTRACT_CHARGES WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN');
PROMPT CFTBS_CONTRACT_INTEREST
SELECT * FROM CFTBS_CONTRACT_INTEREST WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN');
PROMPT BCTM_PRODUCT_MASTER
SELECT * FROM BCTM_PRODUCT_MASTER WHERE PROD_CODE = UPPER(SUBSTR('&CRN',4,4));
PROMPT BCTM_PRODUCT_STATUS_ACENTRIES
SELECT * FROM BCTM_PRODUCT_STATUS_ACENTRIES WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4));
PROMPT cstms_product_event_acct_entry
select * from cstms_product_event_acct_entry  WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
order by event_code,amt_tag,dr_cr_indicator;
PROMPT BCTM_BRANCH_PARAMETERS
SELECT * FROM bctms_branch_parameters WHERE branch = UPPER(SUBSTR('&CRN',1,3));

PROMPT CSTM_PRODUCT_ACCROLE 
SELECT * FROM CSTM_PRODUCT_ACCROLE WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
ORDER BY PRODUCT_CODE, ACCOUNTING_ROLE, STATUS ;

PROMPT CSTM_PRODUCT_EVENT_ADVICE 
SELECT * FROM CSTM_PRODUCT_EVENT_ADVICE WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
ORDER BY PRODUCT_CODE, EVENT_CODE, MSG_TYPE ;

PROMPT CSTB_CONTRACT_EVENT_ADVICE
SELECT * FROM CSTB_CONTRACT_EVENT_ADVICE WHERE CONTRACT_REF_NO = UPPER('&CRN')
ORDER BY CONTRACT_REF_NO, EVENT_SEQ_NO, MSG_TYPE ;

PROMPT MSTB_DLY_MSG_OUT 
SELECT * FROM MSTB_DLY_MSG_OUT WHERE REFERENCE_NO = UPPER('&CRN')
ORDER BY DCN, RUNNING_NO ;

PROMPT MSTB_ARCHIVE_OUT 
SELECT * FROM MSTB_ARCHIVE_OUT WHERE REFERENCE_NO = UPPER('&CRN');

PROMPT CSTB_CONTRACT_EXCEPTION 
SELECT * FROM CSTB_CONTRACT_EXCEPTION WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CSTB_CONTRACT_CHANGE_LOG
SELECT * FROM CSTB_CONTRACT_CHANGE_LOG WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CSTB_CONTRACT_OVD
select * from CSTB_CONTRACT_OVD where contract_ref_no =UPPER('&CRN');

PROMPT TAX TABLES
select * from tatbs_txnrule where contract_ref_no = UPPER('&CRN');

select * from tatbs_txnrule_detail where contract_ref_no = UPPER('&CRN');

PROMPT LMTB_LINE_UTILS

SELECT * FROM LMTB_LINE_UTILS where ref_no =UPPER('&CRN');

Select * from BCTMS_PRODUCT_TRACERS  where product = UPPER(SUBSTR('&CRN',4,4));

PROMPT STATUS TABLES
Select * from CSTMS_PRODUCT_STATUS_MASTER where product = UPPER(SUBSTR('&CRN',4,4));

Select * from CSTMS_PRODUCT_STATUS_COMPS  where product = UPPER(SUBSTR('&CRN',4,4));

Select * from CSTMS_PRODUCT_STATUS_GL where product = UPPER(SUBSTR('&CRN',4,4));

Select * from CSTMS_PRODUCT_STATUS_ADVICES where product = UPPER(SUBSTR('&CRN',4,4));

select * from cstms_contract_userdef_fields where contract_ref_no =UPPER('&CRN') ;

PROMPT CREDIT FUNCTION TABLES

SELECT * FROM cstbs_crfn_txn_master
WHERE contract_ref_no =UPPER('&CRN') ;

SELECT * FROM CSTBS_CRFN_TXN_HANDOFF
WHERE contract_ref_no =UPPER('&CRN') ;

SELECT * FROM CSTBS_CRFN_APPR_RESP
WHERE contract_ref_no =UPPER('&CRN') ;

PROMPT CHARGE TABLES
SELECT * FROM CFTM_PRODUCT_ICCF WHERE PRODUCT = SUBSTR('&CRN',4,4);

SELECT * FROM CFTMS_PRODUCT_CHARGE WHERE PRODUCT = SUBSTR('&CRN',4,4);

select * from CFTBS_CHARGE_APPLN where CONTRACT_REF_NO = UPPER('&CRN') ;

select * from cftbs_charge_assoc where CONTRACT_REF_NO = UPPER('&CRN') ;

select * from CFTBS_CHARGE_LIQD_MASTER where CONTRACT_REF_NO = UPPER('&CRN') ;

select * from cftms_product_charge where product = UPPER(SUBSTR('&CRN',4,4)) ;

SELECT * FROM CFTBS_CONTRACT_CHARGES WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN');

set echo off
spool off

