
accept PROD PROMPT 'Enter the Product Code ==> '
set array 1
set line 5000
set head on
set pagesize 10000
set feedback on
SPOOL /tmp/BCPROD_DETAILS..&PROD..SPL
PROMPT BCTM_BRANCH_PARAMETERS
SELECT * FROM BCTM_BRANCH_PARAMETERS;
PROMPT CSTM_PRODUCT
SELECT * FROM CSTM_PRODUCT WHERE PRODUCT_CODE = '&PROD';
PROMPT BCTM_PRODUCT_MASTER
SELECT * FROM BCTM_PRODUCT_MASTER WHERE PROD_CODE = '&PROD';
PROMPT BCTM_PRODUCT_STATUS_ACENTRIES
SELECT * FROM BCTM_PRODUCT_STATUS_ACENTRIES WHERE PRODUCT_CODE = '&PROD';
PROMPT cstms_product_event_acct_entry
select * from cstms_product_event_acct_entry  WHERE PRODUCT_CODE = '&PROD';
PROMPT BCTM_PRODUCT_DOCS
SELECT * FROM BCTM_PRODUCT_DOCS WHERE PROD_CODE='&PROD';
PROMPT BCTM_PRODUCT_DOCS_CLAUSES
SELECT * FROM BCTM_PRODUCT_DOCS_CLAUSES WHERE PROD_CODE='&PROD';
PROMPT BCTM_PRODUCT_FFT
SELECT * FROM BCTM_PRODUCT_FFT WHERE PROD_CODE='&PROD';
PROMPT BCTM_PRODUCT_INS
SELECT * FROM BCTM_PRODUCT_INS WHERE PROD_CODE='&PROD';
PROMPT BCTM_PRODUCT_TRACERS
SELECT * FROM BCTM_PRODUCT_TRACERS WHERE PROD_CODE='&PROD';

SPOOL OFF

