SET VERIFY OFF
ACCEPT FROM_BRN CHAR PROMPT 'Copy from branch ==> '
ACCEPT TO_BRN CHAR PROMPT 'Copy to branch ==> '

PROMPT HOLIDAY MAINT

DELETE STTM_LCL_HOL_MASTER WHERE BRANCH_CODE = '&TO_BRN';
INSERT INTO STTM_LCL_HOL_MASTER
	(
	AUTH_STAT,
	BRANCH_CODE,
	YEAR,
	MOD_NO,
	RECORD_STAT,
	WEEKLY_HOLIDAYS,
	CHECKER_DT_STAMP,
	CHECKER_ID,
	MAKER_DT_STAMP,
	MAKER_ID,
	ONCE_AUTH,
	UNEXP_HOL
	)
SELECT	AUTH_STAT,
	'&TO_BRN',
	YEAR,
	MOD_NO,
	RECORD_STAT,
	WEEKLY_HOLIDAYS,
	CHECKER_DT_STAMP,
	CHECKER_ID,
	MAKER_DT_STAMP,
	MAKER_ID,
	ONCE_AUTH,
	UNEXP_HOL
FROM	STTM_LCL_HOL_MASTER
WHERE	BRANCH_CODE = '&FROM_BRN'
/

DELETE STTM_LCL_HOLIDAY WHERE BRANCH_CODE = '&TO_BRN'
/

INSERT INTO STTM_LCL_HOLIDAY
	(
	BRANCH_CODE,
	YEAR,
	MONTH,
	HOLIDAY_LIST
	)
SELECT	'&TO_BRN',
	YEAR,
	MONTH,
	HOLIDAY_LIST
FROM	STTM_LCL_HOLIDAY
WHERE	BRANCH_CODE = '&FROM_BRN'
/
