SELECT 'GLS' X, A.GL_CODE, A.CCY_CODE,A.BRANCH_CODE, (A.CR_BAL_LCY - A.DR_BAL_LCY) GLTB_BAL, L ACVW_BAL
FROM GLTB_GL_BAL A,
(
SELECT  AC_NO, AC_BRANCH,AC_CCY,CATEGORY,
        SUM(DECODE(DRCR_IND,'D',-1,1)*LCY_AMOUNT) L
FROM    ACVW_ALL_AC_ENTRIES
WHERE BALANCE_UPD = 'U'
AND CUST_GL = 'G'
and trn_dt <= '30-JUN-2006'
GROUP BY AC_NO, AC_BRANCH,AC_CCY,CATEGORY
) B
WHERE A.GL_CODE = B.AC_NO
AND A.BRANCH_CODE = B.AC_BRANCH
AND A.CCY_CODE = B.AC_CCY
AND (CR_BAL_LCY - DR_BAL_LCY) <> L
AND FIN_YEAR||PERIOD_CODE = fin_year||'M06'
AND B.CATEGORY||(SELECT BRANCH_LCY FROM STTM_BRANCH WHERE BRANCH_CODE = A.BRANCH_CODE) NOT IN ('3'||B.AC_CCY,'4'||B.AC_CCY)
UNION ALL
SELECT 'INC EXP LCY', GL_CODE, CCY_CODE,BRANCH_CODE, (CR_BAL_LCY - DR_BAL_LCY) GLTB_BAL, L ACVW_BAL
FROM GLTB_GL_BAL A,
(
SELECT  AC_NO, AC_BRANCH,CATEGORY,
        SUM(DECODE(DRCR_IND,'D',-1,1)*LCY_AMOUNT) L
FROM    ACVW_ALL_AC_ENTRIES
WHERE BALANCE_UPD = 'U'
AND CUST_GL = 'G'
and trn_dt <= '30-JUN-2006'
GROUP BY AC_NO, AC_BRANCH,CATEGORY
) B
WHERE A.GL_CODE = B.AC_NO
AND A.BRANCH_CODE = B.AC_BRANCH
AND A.CCY_CODE = (SELECT BRANCH_LCY FROM STTM_BRANCH WHERE BRANCH_CODE = A.BRANCH_CODE)
AND (CR_BAL_LCY - DR_BAL_LCY) <> L
AND FIN_YEAR||PERIOD_CODE = fin_year||'M06'
AND B.CATEGORY IN ('3','4')
UNION ALL
SELECT 'CUSTAC', CUST_AC_NO, CCY, BRANCH_CODE, LCY_CURR_BALANCE CUST_AC_BAL, L ACVW_BAL
FROM STTM_CUST_ACCOUNT A,
(
SELECT  AC_NO, AC_BRANCH,AC_CCY,CATEGORY,
        SUM(DECODE(DRCR_IND,'D',-1,1)*LCY_AMOUNT) L
FROM    ACVW_ALL_AC_ENTRIES
WHERE BALANCE_UPD = 'U'
AND CUST_GL = 'A'
and trn_dt <= '30-JUN-2006'
GROUP BY AC_NO, AC_BRANCH,AC_CCY,CATEGORY
) B
WHERE A.CUST_AC_NO = B.AC_NO
AND A.BRANCH_CODE = B.AC_BRANCH
AND A.CCY = B.AC_CCY
AND NVL(LCY_CURR_BALANCE,0) <> NVL(L,0)
/
select BRANCH_CODE,gl_code, ccy_code,x, y, x-y
from
(
SELECT BRANCH_CODE, gl_code, ccy_code, CR_BAL_LCY - dR_BAL_LCY x
FROM GLTB_gL_BAL G WHERE FIN_YEAR||PERIOD_CODE = fin_year||'M06'
AND leaf = 'Y' and gl_code in (select gl_code from gltm_glmaster
where customer = 'C')
) a,
(SELECT SUM(L) y,GL,ccy, BRANCH_CODE BRN FROM
(
SELECT BRANCH_CODE, ccy, LCY_CURR_BALANCE L, DECODE(SIGN(ACY_CURR_BALANCE),-1,DR_GL,CR_GL) GL
FROM STTM_CUST_ACCOUNT
)
GROUP BY GL,ccy, BRANCH_CODE
) b
where gl_code = gl
AND CCY = CCY_CODE
AND BRN = BRANCH_CODE
AND X-Y <> 0
/
