
accept CRN PROMPT 'Enter the CL Account No ==> '
set head on
set array 1
set linesize 10000
set pagesize 50000
set long 10000
set echo on
set trimspool on
set colsep ';'
set numformat 9999999999999999.99
SPOOL /tmp/CLACC_DETAILS..&CRN..SPL
SELECT * FROM ACVW_ALL_AC_ENTRIES WHERE RELATED_ACCOUNT='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_APPS_MASTER WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMP_BALANCES  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMP_BAL_SUMMARY WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMP_CALC  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_COMP_SCH  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_DSBR_DETAIL  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_DSBR_MASTER   WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_EVENTS_DIARY  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_ROLL WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_SCHEDULES_BAL  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_UDE_EFF_DATES  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ACCOUNT_VAMD WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_AMOUNT_PAID WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_AMOUNT_RECD WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_EVENT_ENTRIES  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_EVENT_OVD WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_EXCEPTION_LOG  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_LIQ_SUSPENSION WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_MANUAL_STCH  WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_MANUAL_STSH WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_PROCESSED_REVISIONS WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_REVISION_ACCOUNTS   WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_REVN_SCHEDULES WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ROLL_COMPONENTS WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ROLL_COMP_SETTLED WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_ROLL_SETTLEMENTS WHERE ACCOUNT_NUMBER='&CRN' ;
SELECT * FROM CLTB_SETTLEMENT_EXCEPTION WHERE ACCOUNT_NUMBER='&CRN' ;
set echo off
spool off

