accept CRN PROMPT 'Enter the CL Account No ==> '
set head on
set array 1
set linesize 10000
set pagesize 50000
set long 10000
set echo on
set trimspool on
set colsep ';'
set numformat 9999999999999999.99
SPOOL /tmp/CLACC_DETAILS.&CRN..SPL

SELECT * FROM CLTB_ACCOUNT_ADVICE_SUPPRESS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_APPS_MASTER WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_CHANGE_LOG WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMPONENTS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMPONENTS_AMND WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_BALANCES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_BAL_CRAC WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_BAL_SUMMARY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_CALC  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_SCH  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_SCH_AMND WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_SCH_CRAC WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_COMP_SCH_HISTORY   WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_DSBR_CHARGES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_DSBR_DETAIL  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_DSBR_DETAIL_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_DSBR_MASTER   WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_DSBR_MASTER_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_EVENTS_ADVICES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_EVENTS_DIARY  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_EVENT_USERDEF  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_HOL_PERDS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_HOL_PERDS_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_LINKAGES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_LINKAGES_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_LINKAGES_HISTORY   WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_MASTER_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_MASTER_AMND_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_PARTIES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_PARTIES_AMND WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_PARTIES_HISTORY  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_PROMOTIONS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_PROMOTIONS_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_ROLL WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_ROLL_COMP WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_ROLL_COMP_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCHEDULES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCHEDULES_AMND WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCHEDULES_BAL  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCHEDULES_CRAC WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCHEDULES_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_SCH_BAL_CRAC WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_STCH_CHARGES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_STSH_CHARGES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_UDE_EFF_DATES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_UDE_VALUES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_UDE_VALUES_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_VAMD WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACCOUNT_VAMD_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_COMPONENTS_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_COMP_SCH_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_DSBR_CHARGES_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_HOL_PERDS_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_HOL_PERDS_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_LINKAGES_AMND_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_PARTIES_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_PROMOTIONS_AMND WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_PROMOTIONS_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_ROLL_COMP_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_SCHEDULES_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_UDE_EFFDT_AMND_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_UDE_EFF_DATES_AMND  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_UDE_EFF_DATES_HISTORY  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_UDE_VALUES_AMND_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ACC_UDE_VALUES_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ADHOC_CHARGES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_AMOUNT_PAID WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_AMOUNT_PAID_HISTORY  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_AMOUNT_RECD WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_AMOUNT_RECD_HISTORY  WHERE ACCOUNT_NUMBER='&CRN' ;

--SELECT * FROM CLTB_BCH_TAX   WHERE ACCOUNT_NUMBER='&CRN' ;

--SELECT * FROM CLTB_BCH_TAX_HISTORY  WHERE ACCOUNT_NUMBER='&CRN' ;

--SELECT * FROM CLTB_BCH_TAX_REVERSED WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_CALC_DATES  WHERE ACCOUNT_NUMBER='&CRN' ;

--SELECT * FROM CLTB_CLEARING_EXCEPTION  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_COMP_BALANCES_HISTORY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_DISBR_SCHEDULES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_DISBR_SCHEDULES_AMND   WHERE ACCOUNT_NUMBER='&CRN' ;                                                                        

SELECT * FROM CLTB_DISBR_SCH_AMND_HIST  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_EVENT_CHECK_LIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_EVENT_ENTRIES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_EVENT_OVD WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_EVENT_REMARKS  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_EXCEPTION_LOG  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_IFACEQRY_ONLINE_CALC WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_INACTIVE_EVENTS_DIARY   WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ_COMP_SETTLED WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ_COMP_SUMMARY WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ_PENAL_RATES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ_SETTLEMENTS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_LIQ_SUSPENSION WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_MANUAL_STCH  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_MANUAL_STSH WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_MANUAL_STSH_CHARGES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_PROCESSED_REVISIONS WHERE ACCOUNT_NUMBER='&CRN' ;

--SELECT * FROM CLTB_RECON  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_REVISION_ACCOUNTS   WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_REVN_SCHEDULES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_REVN_SCHEDULES_AMND WHERE ACCOUNT_NUMBER='&CRN' ;                                                                           

SELECT * FROM CLTB_REVN_SCH_AMND_HIST WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ROLL_COMPONENTS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ROLL_COMP_SETTLED WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_ROLL_SETTLEMENTS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTB_SETTLEMENT_EXCEPTION WHERE ACCOUNT_NUMBER='&CRN' ;

-- SELECT * FROM CLTB_UDE_CASCADED_ACCS WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTC_ACCOUNT_COMP_BALANCES WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTC_ACCOUNT_SCHEDULES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTG_ACCOUNT_COMP_BALANCES  WHERE ACCOUNT_NUMBER='&CRN' ;                                                                        

SELECT * FROM CLTG_ACCOUNT_SCHEDULES  WHERE ACCOUNT_NUMBER='&CRN' ;

SELECT * FROM CLTG_AMOUNT_PAID WHERE ACCOUNT_NUMBER='&CRN' ; 

SELECT * FROM ACVWS_ALL_AC_ENTRIES WHERE RELATED_ACCOUNT='&CRN' ;  

set echo off
spool off
