accept CRN PROMPT 'Enter the Product Code ==> '
set head on
set array 1
set linesize 10000
set pagesize 50000
set long 10000
set echo on
set trimspool on
set colsep ';'
set numformat 9999999999999999.99
SPOOL /tmp/CLPROD_DETAILS.&CRN..SPL


SELECT * FROM CLTM_PRODUCT WHERE PRODUCT_CODE='&CRN' ;

-- SELECT * FROM CLTM_PRODUCT_AUTH_REKEY WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_BILLNOTC_MASTER WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_BILLNOTC_RULES WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_BNTC WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_BRN_RESTR WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_CATEGORY WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_CATEGORY_COMP WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_CAT_POLICIES WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_CAT_RESTR   WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_COMPONENTS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_COMP_FRM WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_COMP_FRM_ELEMS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_COMP_FRM_EXPR WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_CUST_RESTR  WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_DELINNOTC_MASTER WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_DELINNOTC_RULES  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_DFLT_SCHEDULES  WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_DNTC WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENTS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_ACCTRULES  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_ADVRULES WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_CHGS   WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_POLCS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_RULES_ADV WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_RULES_ENTRY  WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_EVENT_RULES_ENT_B  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_EVENT_UDF  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_HOL_PERDS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_INSTALL_STATUS   WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_LIQ_ORDER   WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_MCR_MASTER WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_MCR_RULE     WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_MCR_VALUES   WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_OTHSTMT_MASTER    WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_OTHSTMT_RULES  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_ROLL_COMP   WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_RTH  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_RTH_EXPR  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_RULE  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_SDE WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STATUS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STATUS_LEVEL  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STCH_ACCT_ENTRY  WHERE PRODUCT_CODE='&CRN' ;

--SELECT * FROM CLTM_PRODUCT_STCH_ACCT_ENTRY_B  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STCH_ADV  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STCH_CHGS  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STCH_POLCS WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STMT WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STSH_ACCT_ENTRY WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STSH_CHGS WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_STSH_POLCS WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDE  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDE_DATES WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDE_MASTER  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDE_RULES  WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDE_VALUES WHERE PRODUCT_CODE='&CRN' ;

SELECT * FROM CLTM_PRODUCT_UDF WHERE PRODUCT_CODE='&CRN' ;


set echo off
spool off
