SET LINE 9999
SELECT	COUNT(1),
	CONVERSION_STATUS_FLAG
FROM	STTM_UPLOAD_CUSTOMER
GROUP BY CONVERSION_STATUS_FLAG
/

SELECT	CUSTOMER_NO, SUBSTR(ERR_MSG,1,20) ER, MESSAGE
FROM	STTM_UPLOAD_CUSTOMER A,
	ERTB_MSGS B
WHERE	A.ERR_MSG = B.ERR_CODE (+)
AND	CONVERSION_STATUS_FLAG = 'E'
/
