DECLARE
H NUMBER;
M NUMBER;
C NUMBER;
D DATE;
DT VARCHAR2(1000) := '&DATE';
t NUMBER := 0;
N NUMBER := 0;
TOP NUMBER := 0;
BEGIN
H := 7;
M := 30;
LOOP
N := N+1;
D := TO_DATE(DT||' '||LPAD(TO_CHAR(H),2,'0')||':'||LPAD(TO_CHAR(M),2,'0'),'DD-MON-RRRR HH24:MI');
SELECT COUNT(1) INTO C FROM SMTB_CURRENT_USERS_HISTORY WHERE D BETWEEN START_TIME AND NVL(END_TIME,SYSDATE+1);
DBMS_OUTPUT.PUT_LINE(TO_CHAR(D,'DD-MON-RRRR HH24:MI') ||' '|| C);
T := T+C;
IF C > TOP THEN TOP := C; END IF;
M := M +5 ;
IF M = 60 THEN M := 0; H := H+1; END IF;
IF H = 20 THEN EXIT; END IF;
IF D > SYSDATE THEN EXIT; END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE('AVG '||CEIL(T/N));
DBMS_OUTPUT.PUT_LINE('TOP '||TOP);
END;
/
