SET TRIMSPOOL ON PAGES 0 LINE 9999 FEED OFF
SPOOL TMP.TMP
SELECT 'UPDATE SMTB_CONTROL_CLERKS SET CTL_PASSWORD_1 = SMPKS.FN_ENCRYPT_PASSWORD(''PASSWORD'',''AAAAAA''), CTL_PASSWORD_2 = SMPKS.FN_ENCRYPT_PASSWORD(''PASSWORD'',''ZZZZZZ'');'
FROM SMTB_CONTROL_CLERKS
--WHERE CTL_PASSWORD_1||CTL_PASSWORD_2 = '2C4E6y9b1b2b1w2V2b2X0F1C1Z3y5Z7Z9V1C2C1Z2b2E0F0Z'
/
SPOOL OFF
SET FEED ON
@TMP.TMP
COMMIT;
SPOOL TMP.TMP
REM
SPOOL OFF
