undef file
ACCEPT FILE CHAR PROMPT 'File Name ==> '
SET SERVEROUT ON LINE 9999 PAGES 0 FEED OFF TRIMSPOOL ON VERIFY OFF
SPOOL C:\TMP.BAT
SELECT 'IF EXIST \\192.168.2.24\e$\CONSOL\FMXTEMP\ENG\&&file move /Y \\192.168.2.24\e$\CONSOL\FMXTEMP\ENG\&&file \\192.168.2.24\e$\CONSOL\FMXTEMP\ENG\&&file'||'.'||to_char(SYSDATE,'DDMONYYHH24MISS')
FROM DUAL;
PROMPT copy D:\IFLEX\EAB\CHECKIN\FMB\&&file \\192.168.2.24\e$\CONSOL\FMXTEMP\ENG
SPOOL OFF
SET FEED ON SERVEROUT ON
host('C:\tmp.bat')
