SET HEAD OFF
SET FEED OFF
SET TRIMSPOOL ON
SET VERIFY OFF
SPOOL CV1.SQL
select'
SPOOL C:\SOURCE\T\'||OBJECT_NAME||'.SQL
PROMPT CREATE OR REPLACE
SELECT TEXT FROM USER_SOURCE WHERE NAME = '||CHR(39)||OBJECT_NAME||CHR(39)||' AND TYPE = '||CHR(39)||'PACKAGE BODY'||CHR(39)||' ORDER BY LINE'||CHR(59)||'
PROMPT /
SPOOL OFF'
FROM USER_OBJECTS WHERE --OBJECT_NAME LIKE 'ACPK%' AND 
OBJECT_TYPE = 'PACKAGE BODY'
/
SPOOL OFF
