SET SERVEROUT ON SIZE 1000000
DECLARE
	C INTEGER ; --:= DBMS_SQL.OPEN_CURSOR;
	SSQL VARCHAR2(255);
	I INTEGER;
	CURSOR INVOB IS
		SELECT /*'ALTER '|| DECODE (OBJECT_TYPE,'PACKAGE BODY','PACKAGE',OBJECT_TYPE)
			|| ' ' || OBJECT_NAME || ' ' ||
			DECODE (OBJECT_TYPE, 'PACKAGE BODY', 'COMPILE BODY;','COMPILE') SQLSTR*/
			OBJECT_TYPE, OBJECT_NAME
		FROM USER_OBJECTS
		WHERE
		STATUS  = 'INVALID'
		ORDER BY OBJECT_TYPE;

BEGIN
FOR X IN INVOB LOOP
BEGIN
		IF DBMS_SQL.IS_OPEN(C) THEN
			DBMS_SQL.CLOSE_CURSOR(C);
		END IF;

	C := DBMS_SQL.OPEN_CURSOR;	
	SELECT  'ALTER '|| DECODE (X.OBJECT_TYPE,'PACKAGE BODY','PACKAGE',X.OBJECT_TYPE)
			|| ' ' || X.OBJECT_NAME || ' ' ||
			DECODE (X.OBJECT_TYPE, 'PACKAGE BODY', 'COMPILE BODY','COMPILE')
	INTO SSQL FROM DUAL;

	DBMS_SQL.PARSE(C,SSQL,DBMS_SQL.NATIVE);
	I := DBMS_SQL.EXECUTE(C);

	DBMS_SQL.CLOSE_CURSOR(C);
	DBMS_OUTPUT.PUT_LINE ('SUCCESSFUL '||SSQL);
EXCEPTION
	WHEN OTHERS THEN
--		DBMS_OUTPUT.PUT_LINE('FAILED '||SQLERRM);
		IF DBMS_SQL.IS_OPEN(C) THEN
			DBMS_SQL.CLOSE_CURSOR(C);
		END IF;
END;
END LOOP;
END;
/
