DECLARE
	CURSOR_HANDLE	INTEGER	:= DBMS_SQL.OPEN_CURSOR;
	OUT_PUT		INTEGER;
	L_CALCVAL	VARCHAR2(100);
BEGIN
	DBMS_SQL.PARSE(CURSOR_HANDLE, 'SELECT TRN_CODE FROM STTM_TRN_CODE' , DBMS_SQL.NATIVE);
	DBMS_SQL.DEFINE_COLUMN(CURSOR_HANDLE,1,L_CALCVAL,20);
	OUT_PUT := DBMS_SQL.EXECUTE(CURSOR_HANDLE);
	WHILE (DBMS_SQL.FETCH_ROWS(CURSOR_HANDLE)>0)
	LOOP
		DBMS_SQL.COLUMN_VALUE(CURSOR_HANDLE, 1, L_CALCVAL);
		DBMS_OUTPUT.PUT_LINE('== '||L_CALCVAL);
	END LOOP;
	DBMS_SQL.CLOSE_CURSOR(CURSOR_HANDLE);
EXCEPTION
	WHEN OTHERS THEN
		DBMS_SQL.CLOSE_CURSOR(CURSOR_HANDLE);
		DBMS_OUTPUT.PUT_LINE('D' ||SQLERRM);
END;
/
