DECLARE
	FLEXCUBE_U	VARCHAR2(100) := UPPER('&FLEXCUBE_USERNAME');
	FLEXCUBE_P	VARCHAR2(100) := UPPER('&FLEXCUBE_PASSWORD');
	FLEXCUBE_H	VARCHAR2(100) := UPPER('&FLEXCUBE_HOSTNAME');

	EU	VARCHAR2(100);
	EP	VARCHAR2(100);
BEGIN
	EU := SMPKS.FN_ENCRYPT_APP_PASSWORD (FLEXCUBE_U,'CITIL');
	EP := SMPKS.FN_ENCRYPT_APP_PASSWORD (FLEXCUBE_P,FLEXCUBE_U);
	UPDATE	STTMS_HOST
	SET		USERNAME = EU,
			PASSWORD = EP,
			HOST_NAME = FLEXCUBE_H;
--	WHERE		HOST_NAME = FLEXCUBE_H;

--	COMMIT;
END;
/
