SET SERVEROUT ON SIZE 1000000
SET FEED OFF PAGES 0 LINE 9999 TRIMSPOOL ON
SPOOL TMP.TMP
SELECT 'SPOOL D:\TEMP\EODT_'||TO_CHAR(STARTTIME,'DD-MON-RR')||'.SPL' FROM AETB_PROCESS_PROGRESS WHERE ROWNUM = 1;
SPOOL OFF

@TMP.TMP

SET FEED ON PAGES 100 line 100

SELECT BRANCH BR, PROCESS PR, TO_CHAR(STARTTIME,'DD-MON-RRRR HH24:MI:SS') ST, TO_CHAR(ENDTIME,'DD-MON-RRRR HH24:MI:SS') ET,
ROUND(((ENDTIME - STARTTIME)*24*60),2) DUR
FROM AETB_PROCESS_PROGRESS
ORDER BY 5 DESC
/

SPOOL OFF
