 SELECT UNITHOLDERID ,
    (SELECT SUM(SUM(UnitsIn-UnitsOut)*B.PRICE) HOLDINGS
    FROM UHBalLedgerTbl A, SUCCESSIONPRICETBL B
    WHERE
    A.UNITHOLDERID = C.UNITHOLDERID	
    AND A.FUNDID = B.FUNDID
    AND TransactionDate <= '31-DEC-2001'
    GROUP BY B.FUNDID,B.PRICE ) HOLDINGSVALUE
 FROM UNITHOLDERTBL C WHERE C.AUTHREJECTSTATUS = 'A'
/
