SELECT 
USER OWNER,NAME,TYPE,LINE,TEXT T  
FROM USER_SOURCE   
WHERE TYPE IN ('PROCEDURE','FUNCTION','
PACKAGE','PACKAGE BODY')
AND UPPER(TEXT) LIKE UPPER('%&STRING%')
and upper(name) like UPPER('%&NAME%')
ORDER BY 1,2,3,4
/
