create or replace
FUNCTION FN_TBAL(P_DT DATE) RETURN BOOLEAN IS
CURSOR CCY_CUR IS
SELECT DISTINCT AC_CCY FROM ACTB_HISTORY WHERE TRN_DT = P_DT;
BEGIN
IF NOT FN_REBUILD_ACCBAL_FULL('100') THEN
   RETURN FALSE;
END IF;
UPDATE ACTBS_ACCBAL_HISTORY SET
ACY_OPENING_BAL = LCY_OPENING_BAL,
ACY_CLOSING_BAL = LCY_CLOSING_BAL,
ACY_DR_TUR = LCY_DR_TUR,
ACY_CR_TUR = LCY_CR_TUR
WHERE ACC_CCY = 'EUR';
DELETE TBAL WHERE DT = P_DT;
FOR X IN CCY_CUR LOOP
   DECLARE
   CURSOR AC_CUR IS
   SELECT DISTINCT AC_NO, CUST_GL
   FROM  ACTB_HISTORY WHERE TRN_DT = P_DT
           AND AC_CCY = X.AC_CCY;
 L_GL VARCHAR2(10);
 L_CNT NUMBER;
   BEGIN
           FOR Y IN AC_CUR LOOP

  IF Y.CUST_GL = 'A' THEN
   SELECT DR_GL INTO L_GL FROM STTM_CUST_ACCOUNT WHERE CUST_AC_NO = Y.AC_NO;
  ELSE
   L_GL := Y.AC_NO;
  END IF;

  SELECT COUNT(1) INTO L_CNT FROM TBAL WHERE GL = L_GL AND CCY = X.AC_CCY AND DT = P_DT;
  IF L_CNT = 0 THEN
   INSERT INTO TBAL(GL,CCY,DT,OPBAL,DRMOV,CRMOV,CLOSBAL)
   VALUES (L_GL, X.AC_CCY, P_DT, FN_OPBAL(L_GL,P_DT,X.AC_CCY), FN_DR_MOV(L_GL,P_DT,X.AC_CCY),
   FN_CR_MOV(L_GL,P_DT,X.AC_CCY), FN_CLOS_BAL(L_GL,P_DT,X.AC_CCY)
   );
  END IF;
           END LOOP;
   END;
END LOOP;
RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE ('ERROR '||SQLERRM);
RETURN FALSE;
END;
/
