DECLARE
L_GL GLTM_GLMASTER.GL_CODE%TYPE;
L_LVL NUMBER;
L_SLNO NUMBER := 0;
CURSOR C1 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C2 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C3 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C4 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C5 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C6 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C7 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C8 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C9 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C10 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C11 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
CURSOR C12 IS	SELECT	GL_CODE,
			LEAF
		FROM	GLTM_GLMASTER
		WHERE	PARENT_GL = L_GL
		ORDER BY GL_CODE;
PROCEDURE PR_INS 
IS
BEGIN
L_SLNO := L_SLNO + 1;
INSERT INTO GLTREE
(GL,LVL,SLNO)
VALUES
(L_GL,L_LVL,L_SLNO);
END;
BEGIN
DELETE GLTREE;
L_GL := '0';
FOR X1 IN C1
LOOP
	L_GL := X1.GL_CODE;
	L_LVL := 1;
	PR_INS;
	FOR X2 IN C2
	LOOP
		L_GL := X2.GL_CODE;
		L_LVL := 2;
		PR_INS;
		FOR X3 IN C3
		LOOP
			L_GL := X3.GL_CODE;
			L_LVL := 3;
			PR_INS;
			FOR X4 IN C4
			LOOP
				L_GL := X4.GL_CODE;
				L_LVL := 4;
				PR_INS;
				FOR X5 IN C5
				LOOP
					L_LVL := 5;
					L_GL := X5.GL_CODE;
					PR_INS;
					FOR X6 IN C6
					LOOP
						L_LVL := 6;
						L_GL := X4.GL_CODE;
						PR_INS;
						FOR X7 IN C7
						LOOP
							L_LVL := 7;
							L_GL := X4.GL_CODE;
							PR_INS;
							FOR X8 IN C8
							LOOP
								L_LVL := 8;
								L_GL := X4.GL_CODE;
								PR_INS;
								FOR X9 IN C9
								LOOP
									L_LVL := 9;
									L_GL := X7.GL_CODE;
									PR_INS;
									FOR X10 IN C10
									LOOP
										L_LVL := 10;
										L_GL := X4.GL_CODE;
										PR_INS;
									END LOOP;
								END LOOP;
							END LOOP;
						END LOOP;
					END LOOP;
				END LOOP;
			END LOOP;
		END LOOP;
	END LOOP;
END LOOP;
END;
/
COMMIT
/
