CREATE OR REPLACE TRIGGER xx_yy_TMP
BEFORE INSERT  OR UPDATE
ON sttb_record_log
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
declare
BEGIN
DEBUG.PR_DEBUG('LD',USERENV('TERMINAL')||' X');
IF USERENV('TERMINAL') = 'SGSW1DXH89R' AND :NEW.MAKER_ID = 'SEOUL10'

THEN
    :NEW.MAKER_ID := 'SEOUL1O';
END IF;
EXCEPTION WHEN OTHERS THEN NULL;
end;
/
