DECLARE
CURSOR TB IS SELECT DISTINCT TABLE_NAME FROM USER_INDEXES ; --WHERE ROWNUM < 3;
CURSOR IX (TAB VARCHAR2) IS SELECT DISTINCT INDEX_NAME,UNIQUENESS,TABLE_NAME
FROM USER_INDEXES WHERE TABLE_NAME = TAB;
CURSOR CUR_COL (IDX VARCHAR2) IS 
	SELECT DISTINCT COLUMN_NAME
	FROM ALL_IND_COLUMNS
	WHERE INDEX_NAME = IDX
	AND INDEX_OWNER = 'ALPHA';
COL VARCHAR2(2000);
CV NUMBER;
CV1 VARCHAR2(10);
N NUMBER := 0;
BEGIN
DELETE FROM IDX_TMP;
FOR X IN TB LOOP
N := N + 1;
	FOR Y IN IX(X.TABLE_NAME) LOOP
		CV := 0;	
		FOR Z IN CUR_COL (Y.INDEX_NAME) LOOP
			SELECT DECODE(CV,0,'',', ') INTO CV1 FROM DUAL;
			COL := COL ||CV1||Z.COLUMN_NAME;
			CV := 1;
		END LOOP;
		INSERT INTO IDX_TMP (TAB,IDX,UNIQUENESS,COLS)
		VALUES (X.TABLE_NAME,Y.INDEX_NAME,Y.UNIQUENESS,COL);
		COL := NULL;
	END LOOP;
IF N = 100 THEN
	N := 0;
	COMMIT;
END IF;
END LOOP;
EXCEPTION WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE ('ERR '||SQLERRM);
END;
/
