set serverout on feed off verify off
DECLARE
E VARCHAR2(100) := '&ERROR_CODE';
T VARCHAR2(1)   := '&TYPE';
M VARCHAR2(1000) := '&MESSAGE';
BEGIN
INSERT INTO ERTBS_MSGS
(ERR_CODE,LANGUAGE,MESSAGE,TYPE,CONFIRMATION_REQD,FUNCTION_ID,MAX_SUB_PARAM,MODIFIABLE,BATCH_TYPE,DERIVED_MSG,
OVD_CLASS)
VALUES
(E,'ENG',M,T,'N','',0,'N',T,'','N');
DBMS_OUTPUT.PUT_LINE (TO_CHAR(SQL%ROWCOUNT)||' ROW INSERTED');
END;
/

set feed on verify on
