UNDEFINE ACCOUNT
SET VERIFY OFF
SET NUMF 99999999.99
SET LINE 9999
SET FEED OFF
DELETE FROM INTR ;
INSERT INTO INTR (ACC ,DT ,P ,N ,R ,INTR ,CCY ,INTREUR , MABEL)
SELECT CUST_AC_NO,NULL,NULL,NULL,NULL,FCY_AMOUNT,'NLG',LCY_AMOUNT,'M' FROM ICTB_ACQUIRED_INTR_NLG_BACKUP where cust_ac_no = '&&ACCOUNT';
INSERT INTO INTR (ACC ,DT ,P ,N ,R ,INTR ,CCY ,INTREUR , MABEL)
SELECT ACC,FRM_DT,FRM_EL1,DAYS,NULL,FRM_VAL,'NLG',FRM_VAL/2.20371,'F'
FROM ISVALS WHERE ACC = '&&ACCOUNT' AND FRM_DT < '22-OCT-01';
INSERT INTO INTR (ACC ,DT ,P ,N ,R ,INTR ,CCY ,INTREUR , MABEL)
SELECT ACC,FRM_DT,FRM_EL1,DAYS,NULL,FRM_VAL,'EUR',FRM_VAL,'F'
FROM ISVALS WHERE ACC = '&&ACCOUNT' AND FRM_DT >= '22-OCT-01';
UPDATE INTR SET INTREUR = ROUND(INTREUR,2);
UPDATE INTR SET R = ROUND((INTR * 36500)/(P*N),2) WHERE (P*N) <> 0;
SET FEED ON
SELECT * FROM INTR WHERE ACC = '&&ACCOUNT' ORDER BY DT;
SELECT SUM(INTREUR) SUMCALC FROM INTR WHERE ACC = '&&ACCOUNT';
SELECT SUM(LCY_AMOUNT) SUMPASSED FROM ACVW_ALL_AC_ENTRIES WHERE AC_NO = '&&ACCOUNT'
AND TRN_DT = '28-DEC-2001' AND EVENT = 'ILIQ';
UNDEFINE ACCOUNT
SET VERIFY ON
