SET SERVEROUT ON SIZE 1000000 VERIFY OFF
DECLARE
RESULT VARCHAR2(100);
DT DATE := '&DATE';
BEGIN
 IF CEPKS_DATE.fn_isholiday(
			'LCL',
			'804',
			DT,
			result
		)
 THEN
	IF RESULT = 'H'
	THEN
		DBMS_OUTPUT.PUT_LINE(DT ||' IS HOLIDAY');
	ELSE
		DBMS_OUTPUT.PUT_LINE(DT ||' IS WORKING DAY');
	END IF;
 END IF;
END;
/

SET VERIFY ON