
accept CRN PROMPT 'Enter the contract reference no ==> '
set array 1
set line 10000
set pagesize 50000
set long 10000
set echo on
set trimspool on
set head on
set colsep ';'
SPOOL /tmp/LC_DETAILS.&CRN..SPL

PROMPT CSTB_CONTRACT
SELECT * FROM CSTB_CONTRACT WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CSTB_CONTRACT_EVENT_LOG
SELECT * FROM CSTB_CONTRACT_EVENT_LOG WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_CONTRACT_MASTER
SELECT * FROM LCTB_CONTRACT_MASTER WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_AVAILMENTS
SELECT * FROM LCTB_AVAILMENTS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_CLAUSES
SELECT * FROM LCTB_CLAUSES WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_COLLATERAL
SELECT * FROM LCTB_COLLATERAL WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_COMMISSION_MASTER
SELECT * FROM LCTB_COMMISSION_MASTER WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_COMMISSION_DETAILS
SELECT * FROM LCTB_COMMISSION_DETAILS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_DOCUMENTS
SELECT * FROM LCTB_DOCUMENTS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_DRAFTS
SELECT * FROM LCTB_DRAFTS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_DRAFTS_DETAILS
SELECT * FROM LCTB_DRAFTS_DETAILS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_FFTS
SELECT * FROM LCTB_FFTS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_GOODS
SELECT * FROM LCTB_GOODS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_MEMO_ACCRUALS
SELECT * FROM LCTB_MEMO_ACCRUALS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_OTHER_ADDRESSES
SELECT * FROM LCTB_OTHER_ADDRESSES WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_PARTIES
SELECT * FROM LCTB_PARTIES WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_SHIPMENT
SELECT * FROM LCTB_SHIPMENT WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LCTB_TRACERS
SELECT * FROM LCTB_TRACERS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT ACVW_ALL_AC_ENTRIES
SELECT * FROM ACVW_ALL_AC_ENTRIES WHERE TRN_REF_NO = UPPER('&CRN');

PROMPT ACtb_daily_log
SELECT * FROM ACtb_daily_log WHERE TRN_REF_NO = UPPER('&CRN');

PROMPT ACTB_DAILY_GHOST_LOG
select * from actb_daily_ghost_log where trn_ref_no = UPPER('&CRN');

PROMPT ISTBS_CONTRACTIS
SELECT * FROM ISTB_CONTRACTIS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT ISTBS_CONTRACT_DETAILS
SELECT * FROM ISTB_CONTRACT_DETAILS WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT ISTBS_CONTRACTIS_SWIFT
SELECT * FROM ISTB_CONTRACTIS_SWIFT WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT ISTBS_MSGHO
SELECT * FROM ISTB_MSGHO WHERE contract_ref_no = UPPER('&CRN') ORDER BY EVENT_SEQ_NO, MSG_TYPE, RECEIVER, SERIAL_NO;

PROMPT CSTM_PRODUCT
SELECT * FROM CSTM_PRODUCT WHERE PRODUCT_CODE = SUBSTR(UPPER('&CRN'),4,4);

PROMPT cstms_product_event_acct_entry
select * from cstm_product_event_acct_entry  WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
order by event_code,amt_tag,dr_cr_indicator;

PROMPT CSTMS_PRODUCT_EVENT_ADVICE
SELECT * FROM CSTM_PRODUCT_EVENT_ADVICE WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
ORDER BY PRODUCT_CODE, EVENT_CODE, MSG_TYPE ;

PROMPT CSTBS_CONTRACT_EVENT_ADVICE
SELECT * FROM CSTB_CONTRACT_EVENT_ADVICE WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CSTMS_PRODUCT_ACCROLE
SELECT * FROM CSTM_PRODUCT_ACCROLE WHERE PRODUCT_CODE = UPPER(SUBSTR('&CRN',4,4))
ORDER BY PRODUCT_CODE, ACCOUNTING_ROLE, STATUS ;

PROMPT LCTM_PRODUCT_DEFINITION
SELECT * FROM LCTM_PRODUCT_DEFINITION WHERE PRODUCT_CODE =  SUBSTR(UPPER('&CRN'),4,4);


Prompt Product_iccf
select * from cftm_product_iccf WHERE product=SUBSTR(UPPER('&CRN'),4,4);


PROMPT LCTM_PRODUCT_DOCUMENTS
SELECT * FROM LCTM_PRODUCT_DOCUMENTS WHERE PRODUCT_CODE =  SUBSTR(UPPER('&CRN'),4,4);

PROMPT LCTM_PRODUCT_DOC_CLAUSE
SELECT * FROM LCTM_PRODUCT_DOC_CLAUSE WHERE PRODUCT_CODE =  SUBSTR(UPPER('&CRN'),4,4);

PROMPT LCTM_PRODUCT_FFT
SELECT * FROM LCTM_PRODUCT_FFT WHERE PRODUCT_CODE = SUBSTR(UPPER('&CRN'),4,4);

PROMPT LCTM_PRODUCT_TRACERS
SELECT * FROM LCTM_PRODUCT_TRACERS WHERE PRODUCT_CODE = SUBSTR(UPPER('&CRN'),4,4);

PROMPT LCTM_BRANCH_PARAMETERS
SELECT * FROM lctm_branch_parameters WHERE branch = SUBSTR('&CRN',1,3);

PROMPT MSTBS_DAILY_MSG_OUT
SELECT BRANCH,DCN,REFERENCE_NO,ESN,MODULE,MSG_TYPE,PRODUCT,AMOUNT,MEDIA,SWIFT_MSG_TYPE,
GENERATE_STATUS,MSG_STATUS,REPAIR_REASON,HOLD_STATUS FROM MSTBS_DLY_MSG_OUT
WHERE REFERENCE_NO = UPPER('&CRN')ORDER BY DCN, RUNNING_NO;

SELECT * FROM MSTB_DLY_MSG_OUT WHERE REFERENCE_NO = UPPER('&CRN')ORDER BY DCN, RUNNING_NO;

PROMPT MSTBS_ARCHIVE_OUT
SELECT BRANCH,DCN,REFERENCE_NO,ESN,MODULE,MSG_TYPE,PRODUCT,AMOUNT,MEDIA FROM MSTB_DLY_MSG_OUT
WHERE REFERENCE_NO = UPPER('&CRN');

PROMPT CFTB_CONTRACT_INTEREST
SELECT * FROM cftb_contract_INTEREST WHERE contract_reference_no = UPPER('&CRN');

PROMPT CFTB_CONTRACT_CHARGES
SELECT * FROM cftb_contract_charges WHERE contract_reference_no = UPPER('&CRN');

PROMPT CFTB_CONTRACT_Commission
SELECT * FROM cftb_contract_commission WHERE contract_reference_no = UPPER('&CRN');

PROMPT  CSTB_CONTRACT_EVENT_ADVICE
SELECT * FROM  CSTB_CONTRACT_EVENT_ADVICE WHERE contract_ref_no = UPPER('&CRN')
ORDER BY CONTRACT_REF_NO, EVENT_SEQ_NO, MSG_TYPE ;

PROMPT cftbs_contract_commission
SELECT * FROM  cftb_contract_commission WHERE contract_reference_no = UPPER('&CRN') order by component , event_seq_no;

PROMPT cstbs_contract_exception
SELECT * FROM  cstb_contract_exception WHERE contract_ref_no = UPPER('&CRN') order by event_seq_no;

PROMPT tatm_product_tax
SELECT * FROM tatm_product_tax where product = UPPER(SUBSTR('&CRN',4,4));

prompt tatbs_txnrule
SELECT	*  FROM	tatbs_txnrule  WHERE contract_ref_no = UPPER('&CRN');

prompt tatbs_txnrule_detail
SELECT	* FROM	tatbs_txnrule_detail WHERE contract_ref_no = UPPER('&CRN');

SPOOL OFF
set echo off

