@storeset
accept CRN PROMPT 'Enter the contract reference no ==> '
set head on
set array 1
set linesize 10000
set pagesize 50000
set long 10000
set echo on
set trimspool on
set colsep ';'
set numformat 9999999999999999.99
--set feed off markup html on spool on 
--set termout off

SPOOL /tmp/LD_DETAILS.&CRN..xls

PROMPT CSTBS_CONTRAC
SELECT * FROM CSTB_CONTRACT WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_CONTROL
SELECT * FROM LDTB_CONTRACT_CONTROL WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTBS_CONTRACT_EVENT_LOG
SELECT * FROM CSTB_CONTRACT_EVENT_LOG WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_MASTER
SELECT * FROM LDTB_CONTRACT_MASTER WHERE CONTRACT_REF_NO = '&CRN';

PROMPT  ldtbs_contract_amend_due
SELECT * FROM  ldtb_contract_amend_due WHERE CONTRACT_REF_NO = '&CRN';

PROMPT  ldtbs_contract_init_due
SELECT * FROM  ldtb_contract_init_due WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTBS_AMOUNT_DUE
SELECT * FROM CSTB_AMOUNT_DUE WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTBS_TEMP_AMOUNT_DUE
SELECT * FROM CSTB_TEMP_AMOUNT_DUE WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_AMOUNT_DUE
SELECT * FROM LDTBS_AMOUNT_DUE WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LDTBS_TEMP_AMOUNT_DUE
SELECT * FROM LDTBS_TEMP_AMOUNT_DUE WHERE CONTRACT_REF_NO = UPPER('&CRN');


PROMPT CSTBS_AMOUNT_PAID
SELECT * FROM CSTB_AMOUNT_PAID WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_LIQ
SELECT * FROM LDTB_CONTRACT_LIQ WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_LIQ_SUMMARY
SELECT * FROM LDTB_CONTRACT_LIQ_SUMMARY WHERE CONTRACT_REF_NO = '&CRN';

Prompt LDTB_CONTRACT_LIQ_SUMMARY WITH Value Date
SELECT b.VALUE_DATE "Value_date", a.* FROM LDTB_CONTRACT_LIQ a,LDTB_CONTRACT_LIQ_SUMMARY b
WHERE 	a.CONTRACT_REF_NO = '&CRN'
AND		a.contract_ref_no		=	b.contract_ref_no
AND		a.event_seq_no		=	b.event_seq_no
AND		b.payment_status		=	'A';

PROMPT LDTBS_CONTRACT_ACCRUAL_HISTORY
SELECT * FROM LDTB_CONTRACT_ACCRUAL_HISTORY WHERE CONTRACT_REF_NO = '&CRN';

PROMPT ACVWS_ALL_AC_ENTRIES
SELECT * FROM ACVW_ALL_AC_ENTRIES WHERE TRN_REF_NO = '&CRN';

PROMPT ACTBS_DAILY_GHOST_LOG
SELECT * FROM ACTB_DAILY_GHOST_LOG WHERE TRN_REF_NO = '&CRN';

prompt ldtbs_contract_liq
select * from ldtb_contract_liq where CONTRACT_REF_NO = '&CRN';

PROMPT ISTBS_CONTRACTIS
SELECT * FROM ISTB_CONTRACTIS WHERE CONTRACT_REF_NO = '&CRN';

PROMPT ISTBS_MSGHO
SELECT * FROM ISTB_MSGHO WHERE CONTRACT_REF_NO = '&CRN';

PROMPT ISTBS_CONTRACT_DETAILS
SELECT * FROM ISTB_CONTRACT_DETAILS WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_PREFERENCE
SELECT * FROM LDTB_CONTRACT_PREFERENCE WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_SCHEDULES
SELECT * FROM LDTB_CONTRACT_SCHEDULES WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_ICCF_CALC
SELECT * FROM LDTB_CONTRACT_ICCF_CALC WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_TEMP_ICCF_CALC
SELECT * FROM LDTB_TEMP_ICCF_CALC WHERE CONTRACT_REF_NO = '&CRN';

PROMPT LDTBS_CONTRACT_ICCF_DETAILS
SELECT * FROM LDTB_CONTRACT_ICCF_DETAILS WHERE CONTRACT_REF_NO = '&CRN';

PROMPT ldtbs_contract_rule_of_78
SELECT * FROM ldtb_contract_rule_of_78 WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTBS_CONTRACT_EXCEPTIONS
SELECT * FROM CSTB_CONTRACT_EXCEPTION WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTMS_PRODUCT
SELECT * FROM CSTM_PRODUCT WHERE PRODUCT_CODE = SUBSTR('&CRN',4,4);

PROMPT CFTM_PRODUCT_ICCF
SELECT * FROM CFTM_PRODUCT_ICCF WHERE PRODUCT = SUBSTR('&CRN',4,4);

PROMPT LDTMS_PRODUCT_MASTER
SELECT * FROM LDTM_PRODUCT_MASTER WHERE PRODUCT = SUBSTR('&CRN',4,4);

PROMPT ldtms_product_rollover
SELECT * FROM ldtm_product_rollover WHERE PRODUCT = SUBSTR('&CRN',4,4);

PROMPT Ldtbs_Provision_Detail
SELECT * FROM Ldtb_Provision_Detail WHERE CONTRACT_REF_NO = '&CRN';

PROMPT Ldtbs_Provision_History
SELECT * FROM Ldtb_Provision_History WHERE CONTRACT_REF_NO = '&CRN';

PROMPT CSTMS_PRODUCT_EVENT_ACCT_ENTRY
SELECT * FROM CSTM_PRODUCT_EVENT_ACCT_ENTRY WHERE PRODUCT_CODE = SUBSTR('&CRN',4,4)
order by event_code,amt_tag,dr_cr_indicator;

PROMPT CSTMS_PRODUCT_EVENT_ADVICE
SELECT * FROM CSTM_PRODUCT_EVENT_ADVICE WHERE PRODUCT_CODE = SUBSTR('&CRN',4,4)
ORDER BY PRODUCT_CODE, EVENT_CODE, MSG_TYPE ;

PROMPT CSTBS_CONTRACT_EVENT_ADVICE
SELECT * FROM CSTB_CONTRACT_EVENT_ADVICE WHERE CONTRACT_REF_NO = '&CRN'
ORDER BY CONTRACT_REF_NO, EVENT_SEQ_NO, MSG_TYPE ;

PROMPT LDTBS_PERIODIC_ACCRUAL_DATE
SELECT * FROM LDTB_PERIODIC_ACCRUAL_DATE WHERE PRODUCT = SUBSTR('&CRN',4,4);

PROMPT MSTBS_DAILY_MSG_OUT
SELECT * FROM MSTB_DLY_MSG_OUT WHERE REFERENCE_NO = UPPER('&CRN') ORDER BY DCN, RUNNING_NO;

PROMPT MSTBS_ARCHIVE_OUT
SELECT * FROM MSTB_ARCHIVE_OUT WHERE REFERENCE_NO = UPPER('&CRN');

PROMPT contract_balance
SELECT * FROM LDTB_CONTRACT_BALANCE WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LDTBS_AMOUNT_PAID
SELECT * FROM LDTBS_AMOUNT_PAID WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT ISTBS_CONTRACTIS_SWIFT
SELECT * FROM ISTB_CONTRACTIS_SWIFT WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT CFTMS_FLOATING_RATE;
SELECT * FROM CFTM_FLOATING_RATE
WHERE ( RATE_CODE, CCY_CODE ) IN ( SELECT DISTINCT RATE_CODE, CURRENCY FROM CFTB_CONTRACT_INTEREST
							WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN') )
AND BRANCH_CODE = SUBSTR(UPPER('&CRN'),1,3)
ORDER BY RATE_CODE, CCY_CODE, AMOUNT_SLAB, EFFECTIVE_DATE;

PROMPT CFTMS_FLOAT_RATE_MASTER;
SELECT * FROM CFTM_FLOAT_RATE_MASTER
WHERE ( RATE_CODE, CCY_CODE ) IN ( SELECT DISTINCT RATE_CODE, CURRENCY FROM CFTB_CONTRACT_INTEREST
							WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN') )
AND BRANCH_CODE = SUBSTR(UPPER('&CRN'),1,3)
ORDER BY RATE_CODE, CCY_CODE, AMOUNT_SLAB, EFFECTIVE_DATE;

PROMPT CFTMS_FLOAT_RATE_DETAIL;
SELECT * FROM CFTM_FLOAT_RATE_DETAIL
WHERE ( RATE_CODE, CCY_CODE ) IN ( SELECT DISTINCT RATE_CODE, CURRENCY FROM CFTB_CONTRACT_INTEREST
							WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN') )
AND BRANCH_CODE = SUBSTR(UPPER('&CRN'),1,3)
ORDER BY RATE_CODE, CCY_CODE, AMOUNT_SLAB, EFFECTIVE_DATE;

PROMPT CFTBS_CONTRACT_INTEREST
SELECT * FROM CFTB_CONTRACT_INTEREST WHERE CONTRACT_REFERENCE_NO = UPPER('&CRN');

PROMPT LDTBS_CONTRACT_ROLLOVER
SELECT * FROM LDTB_CONTRACT_ROLLOVER WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LDTBS_CONTRACT_ROLL_INT_RATES
SELECT * FROM LDTB_CONTRACT_ROLL_INT_RATES WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT LDTMS_PRODUCT_DFLT_SCHEDULES
SELECT * FROM LDTM_PRODUCT_DFLT_SCHEDULES WHERE PRODUCT = SUBSTR('&CRN',4,4);

PROMPT LDTMS_BRANCH_PARAMETERS
SELECT * FROM ldtm_branch_parameters WHERE branch_CODE = SUBSTR('&CRN',1,3);

PROMPT LDTbs__contract_frrn_due
SELECT * FROM LDTb_contract_frrn_due WHERE contract_ref_no =  UPPER('&CRN');

PROMPT ldTBS_contract_revision_sch
SELECT * FROM ldtb_contract_revision_sch WHERE contract_ref_no =  UPPER('&CRN');

PROMPT CSTMS_PRODUCT_STATUS_ADVICES
SELECT * FROM CSTM_PRODUCT_STATUS_ADVICES WHERE PRODUCT =SUBSTR('&CRN',4,4);

PROMPT CSTMS_PRODUCT_STATUS_COMPS
SELECT * FROM CSTM_PRODUCT_STATUS_COMPS WHERE PRODUCT =SUBSTR('&CRN',4,4);

PROMPT CSTMS_PRODUCT_STATUS_MASTER
SELECT * FROM CSTM_PRODUCT_STATUS_MASTER WHERE PRODUCT =SUBSTR('&CRN',4,4);

PROMPT CSTMS_PRODUCT_STATUS_GL
SELECT * FROM CSTM_PRODUCT_STATUS_GL WHERE PRODUCT =SUBSTR('&CRN',4,4);

PROMPT LDTBS_CONTRACT_STATUS_CHANGE
SELECT * FROM LDTB_CONTRACT_STATUS_CHANGE  WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT MITBS_UNIT_DET_DAILY
SELECT * FROM MITB_UNIT_DET_DAILY WHERE UNIT_REF_NO =  UPPER('&CRN');

PROMPT LDTBS_CONTRACT_ACCRUAL_HISTORY
SELECT * FROM LDTB_CONTRACT_ACCRUAL_HISTORY WHERE CONTRACT_REF_NO = UPPER('&CRN');

PROMPT cstms_product_accrole
SELECT * FROM cstm_product_accrole WHERE product_code = UPPER(SUBSTR('&CRN',4,4))
ORDER BY PRODUCT_CODE, ACCOUNTING_ROLE, STATUS ;

PROMPT cstms_product_accrole
SELECT * FROM cftm_product_iccf WHERE product = UPPER(SUBSTR('&CRN',4,4));

PROMPT ldtbs_contract_linkages
SELECT * FROM LDTB_CONTRACT_LINKAGES WHERE contract_ref_no = UPPER('&CRN') or LINKED_TO_REF = UPPER('&CRN');

SELECT * FROM tftm_deposit_block WHERE ref_no = UPPER('&CRN');

PROMPT ldtbs_contract_linkage_events
SELECT * FROM LDTB_CONTRACT_LINKAGE_EVENTS where contract_ref_no = UPPER('&CRN') OR LINKED_TO_REF = UPPER('&CRN');

prompt mitbs_class_mapping
SELECT * FROM mitb_class_mapping WHERE unit_ref_no = UPPER('&CRN');

prompt MITBS_CONTRACT_FRRN_DUE
SELECT * FROM MITB_CONTRACT_FRRN_DUE WHERE CONTRACT_REF_NO= UPPER('&CRN');

prompt mitbs_dly_refinance_rates
SELECT * FROM mitb_dly_refinance_rates WHERE unit_ref_no = UPPER('&CRN');

prompt  mitbs_unit_head_det
SELECT * FROM  mitb_unit_head_det WHERE unit_ref_no = UPPER('&CRN');

prompt MITBS_UNIT_DET_DAILY
SELECT * FROM MITB_UNIT_DET_DAILY WHERE unit_ref_no = UPPER('&CRN');

prompt MITMS_POOL_DLY_REF_RATES_DTLS
SELECT m.* FROM MITM_POOL_DLY_REF_RATES_DTLS m, ldtb_contract_master l
where l.contract_ref_no=UPPER('&CRN')
and l.event_seq_no=(select max(event_seq_no) from ldtb_contract_master
			where contract_ref_no=l.contract_ref_no)
and m.ccy=l.currency;

prompt mitbs_latest_ref_rate
SELECT m.* FROM mitb_latest_ref_rate m, ldtb_contract_master l
where l.contract_ref_no=UPPER('&CRN')
and l.event_seq_no=(select max(event_seq_no) from ldtb_contract_master
			where contract_ref_no=l.contract_ref_no)
and m.ccy_code=l.currency;

prompt ictms_rates
SELECT i.* FROM ictm_rates i, ldtb_contract_master l
where l.contract_ref_no=UPPER('&CRN')
and l.event_seq_no=(select max(event_seq_no) from ldtb_contract_master
			where contract_ref_no=l.contract_ref_no)
and i.ccy_code=l.currency;

prompt cstms_contract_userdef_fields
select * from cstm_contract_userdef_fields where CONTRACT_REF_NO = '&CRN';

PROMPT ldtbs_contract_assignment
SELECT * FROM ldtb_contract_assignment WHERE  CONTRACT_REF_NO= UPPER('&CRN');

PROMPT tatms_product_tax
SELECT * FROM tatm_product_tax WHERE product = SUBSTR('&CRN',4,4);

PROMPT TATMS_SCHEME_DETAIL
SELECT * FROM TATM_SCHEME_DETAIL;

PROMPT tatm_rule
SELECT * FROM tatm_rule;

PROMPT tatbs_txnrule
SELECT * FROM tatb_txnrule where CONTRACT_REF_NO= UPPER('&CRN');

PROMPT tatbs_txnrule_detail
SELECT * FROM tatb_txnrule_detail where CONTRACT_REF_NO= UPPER('&CRN');

PROMPT TATB_MAINTXN
select * from tatb_maintxn where contract_ref_no = UPPER('&CRN');

PROMPT tatm_slab
SELECT * FROM tatm_slab;

Prompt CFTM_PRODUCT_CURRENCY_LIMITS
SELECT * FROM CFTM_PRODUCT_CURRENCY_LIMITS WHERE product = SUBSTR('&CRN',4,4);

SELECT * FROM STTM_LCL_HOLIDAY WHERE BRANCH_CODE=SUBSTR('&CRN',1,3) AND YEAR = ( SELECT TO_CHAR(TODAY,'YYYY')
FROM STTM_DATES WHERE BRANCH_CODE=SUBSTR('&CRN',1,3));


select * from LDTM_PRODUCT_LIQ_ORDER where product = SUBSTR('&CRN',4,4);

Prompt LDTB_ACCRUAL_FOR_LIMITS
SELECT * FROM LDTB_ACCRUAL_FOR_LIMITS where CONTRACT_REF_NO= UPPER('&CRN');

Prompt CFTB_CHARGE_APPLN
select * from CFTB_CHARGE_APPLN where CONTRACT_REF_NO = UPPER('&CRN') ;

Prompt CFTB_CHARGE_APPLN
select * from LMTB_LINE_UTILS where REF_NO = UPPER('&CRN') ;

set echo off
spool off

@restoreset
