SET TRIMSPOOL ON PAGES 0 LINE 9999 FEED OFF
SPOOL TMP.TMP
SELECT 'UPDATE '||TABLE_NAME||' SET MAKER_ID = '||CHR(39)||'SYSTEM'||CHR(39)||';'
FROM COLS
WHERE COLUMN_NAME = 'MAKER_ID'
/
SELECT 'UPDATE '||TABLE_NAME||' SET CHECKER_ID = '||CHR(39)||'SYSTEM'||CHR(39)||';'
FROM COLS
WHERE COLUMN_NAME = 'CHECKER_ID'
/
SELECT 'UPDATE '||TABLE_NAME||' SET MAKER_DT_STAMP = '||CHR(39)||'02-JUL-2004'||CHR(39)||';'
FROM COLS
WHERE COLUMN_NAME = 'MAKER_DT_STAMP'
/
SELECT 'UPDATE '||TABLE_NAME||' SET CHECKER_DT_STAMP = '||CHR(39)||'02-JUL-2004'||CHR(39)||';'
FROM COLS
WHERE COLUMN_NAME = 'CHECKER_DT_STAMP'
/
SPOOL OFF

SET FEED ON PAGES 100