UPDATE	STTMS_CUSTOMER
SET	CUSTOMER_NAME1 = 'CUSTOMER_'||CUSTOMER_NO,
	SHORT_NAME = CUSTOMER_NO,
	SHORT_NAME2 = CUSTOMER_NO,
	FULL_NAME = 'FULL_NAME_'||CUSTOMER_NO,
	ADDRESS_LINE1 = 'ADDRESS_1_'||CUSTOMER_NO,
	ADDRESS_LINE2 = 'ADDRESS_2_'||CUSTOMER_NO,
	ADDRESS_LINE3 = 'ADDRESS_3_'||CUSTOMER_NO,
	ADDRESS_LINE4 = 'ADDRESS_4_'||CUSTOMER_NO;

UPDATE	STTM_CUST_CORPORATE
SET	CORPORATE_NAME = 'CORP_'|| CUSTOMER_NO;

UPDATE	STTM_CUST_DOMESTIC
SET	SPOUSE_NAME = 'SPOUSE_'||CUSTOMER_NO;

UPDATE	STTM_CUST_PERSONAL
SET	FIRST_NAME = 'FIRST_NAME_'||CUSTOMER_NO,
	MIDDLE_NAME = 'MID_NAME_'||CUSTOMER_NO,
	LAST_NAME = 'LAST_NAME_'||CUSTOMER_NO;

UPDATE	STTM_CUST_PERSONAL_JOINT
SET	FIRST_NAME = 'FIRST_NAME_'||CUSTOMER_NO,
	MIDDLE_NAME = 'MID_NAME_'||CUSTOMER_NO,
	LAST_NAME = 'LAST_NAME_'||CUSTOMER_NO;

UPDATE	STTBS_ACCOUNT
SET	CUST_NAME1 = 'CUSTOMER_'||CUST_NO
WHERE	AC_OR_GL = 'A';

UPDATE	STTMS_CUST_ACCOUNT
SET	AC_DESC = 'ACDESC_'||CUST_AC_NO,
	ADDRESS1 = 'ADDRESS1_'||CUST_AC_NO,
	ADDRESS2 = 'ADDRESS2_'||CUST_AC_NO,
	ADDRESS3 = 'ADDRESS3_'||CUST_AC_NO,
	ADDRESS4 = 'ADDRESS4_'||CUST_AC_NO;

UPDATE	MSTMS_CUST_ADDRESS
SET	ADDRESS1 = DECODE(MEDIA,'MAIL','ADDRESS_1'||CUSTOMER_NO,ADDRESS1),
	ADDRESS2 = DECODE(MEDIA,'MAIL','ADDRESS_2'||CUSTOMER_NO,NULL),
	ADDRESS3 = DECODE(MEDIA,'MAIL','ADDRESS_3'||CUSTOMER_NO,NULL),
	ADDRESS4 = DECODE(MEDIA,'MAIL','ADDRESS_4'||CUSTOMER_NO,NULL);

UPDATE	LCTB_CONTRACT_MASTER
SET	CUST_NAME = 'CUST_NAME_'||CIF_ID;

UPDATE	BCTB_CONTRACT_PARTIES
SET	PARTY_NAME	= 'PARTY_NAME_'||PARTY_ID,
	PARTY_ADDR1	= 'PARTY_ADDR1_'||PARTY_ID,
	PARTY_ADDR2	= 'PARTY_ADDR2_'||PARTY_ID,
	PARTY_ADDR3	= 'PARTY_ADDR3_'||PARTY_ID,
	PARTY_ADDR4	= 'PARTY_ADDR4_'||PARTY_ID;

UPDATE	BRTM_BRMASTER
SET	NAME = 'NAME_'||BROKER;

UPDATE	LCTB_PARTIES
SET	CUST_NAME = 'CUST_NAME_'||CIF_ID,
	CUST_ADDRESS_LIN1 = 'ADDRESS1_'||CIF_ID,
	CUST_ADDRESS_LIN2 = 'ADDRESS2_'||CIF_ID,
	CUST_ADDRESS_LIN3 = 'ADDRESS3_'||CIF_ID,
	CUST_ADDRESS_LIN4 = 'ADDRESS4_'||CIF_ID;

UPDATE	LCTB_TRANSFER_PARTIES
SET	PARTY_NAME = 'PARTY_NAME_'||PARTY_ID,
	ADDRESS1 = 'ADDRESS1_'||PARTY_ID,
	ADDRESS2 = 'ADDRESS2_'||PARTY_ID,
	ADDRESS3 = 'ADDRESS3_'||PARTY_ID;

UPDATE	MSTB_DLY_MSG_OUT
SET	NAME = 'NAME_'||RECEIVER,
	NAME2 = 'NAME2_'||RECEIVER,
	MESSAGE = NULL,
	ADDRESS1 = DECODE(MEDIA,'MAIL','ADDRESS1_'||RECEIVER,ADDRESS1),
	ADDRESS2 = DECODE(MEDIA,'MAIL','ADDRESS2_'||RECEIVER,ADDRESS2),
	ADDRESS3 = DECODE(MEDIA,'MAIL','ADDRESS3_'||RECEIVER,ADDRESS3),
	ADDRESS4 = DECODE(MEDIA,'MAIL','ADDRESS4_'||RECEIVER,ADDRESS4);

UPDATE	MSTB_ARCHIVE_OUT
SET	NAME = 'NAME_'||RECEIVER,
	ADDRESS1 = DECODE(MEDIA,'MAIL','ADDRESS1_'||RECEIVER,ADDRESS1),
	ADDRESS2 = DECODE(MEDIA,'MAIL','ADDRESS2_'||RECEIVER,ADDRESS2),
	ADDRESS3 = DECODE(MEDIA,'MAIL','ADDRESS3_'||RECEIVER,ADDRESS3),
	ADDRESS4 = DECODE(MEDIA,'MAIL','ADDRESS4_'||RECEIVER,ADDRESS4);

UPDATE	CSTB_CONTRACT_EVENT_ADVICE
SET	PARTY_NAME = 'PARTY_NAME_'||PARTY_ID,
	ADDRESS_LINE1 = DECODE(MEDIUM,'MAIL','ADDRESS_1'||PARTY_ID,ADDRESS_LINE1),
	ADDRESS_LINE2 = DECODE(MEDIUM,'MAIL','ADDRESS_2'||PARTY_ID,ADDRESS_LINE1),
	ADDRESS_LINE3 = DECODE(MEDIUM,'MAIL','ADDRESS_3'||PARTY_ID,ADDRESS_LINE1),
	ADDRESS_LINE4 = DECODE(MEDIUM,'MAIL','ADDRESS_4'||PARTY_ID,ADDRESS_LINE1)
WHERE	MSG_TYPE <> 'PAYMENT_MESSAGE';

UPDATE	CSTB_CONTRACT_EVENT_ADVICE
SET	PARTY_NAME = 'PARTY_NAME_'||PARTY_ID
WHERE	MSG_TYPE = 'PAYMENT_MESSAGE';

DELETE	STTB_FIELD_LOG;


