SET TRIMSPOOL ON PAGES 0 LINE 999 FEED OFF
SPOOL #$%.CVR
SELECT 'ALTER INDEX '||INDEX_NAME||' REBUILD TABLESPACE FLEXMLINDEX;'
FROM USER_INDEXES
WHERE TABLESPACE_NAME <> 'FLEXMLINDEX'
/
SPOOL OFF
SET FEED ON
@#$%.CVR
