UNDEF DCN

DECLARE
	L_DCN 		VARCHAR2(16):= '&DCN';
	L_IN_BG_RUNNING	VARCHAR2(1000);
	L_TMP		VARCHAR2(12) := TO_CHAR(SYSDATE,'YYMMDDHH24MISS');
BEGIN
	SELECT	STATUS
	INTO	L_IN_BG_RUNNING
	FROM	MSTB_BG_STATUS
	WHERE	PROCESS = 'IN';
	
	IF L_IN_BG_RUNNING = 'Y'
	THEN
		mspks_dist.pr_stop_bg_in;
	END IF;
	
	DELETE	CSTBS_DEBUG_USERS
	WHERE	USER_ID = L_TMP;
	INSERT	INTO CSTBS_DEBUG_USERS
	SELECT	MODULE,DEBUG,L_TMP
	FROM	CSTBS_DEBUG_USERS
	WHERE	USER_ID = 'UPLOAD';
	DELETE	CSTBS_DEBUG_USERS
	WHERE	USER_ID = 'UPLOAD';
	INSERT	INTO CSTB_DEBUG_USERS
	select	module, 'Y', 'UPLOAD'
	from 	cstb_debug;
	
	GLOBAL.PR_INIT('805','UPLOAD');

	UPDATE	MSTB_DLY_MSG_IN
	SET	STATUS = 'U',
		PROCESS_STATUS = 'U',
		REPAIR_REASON = NULL,
		GENERATED_REF_NO = NULL
	WHERE	DCN = L_DCN;
	
	mspkss.pr_bg_gen_msg_in;
	
	DELETE	CSTBS_DEBUG_USERS
	WHERE	USER_ID = 'UPLOAD';
	INSERT	INTO CSTBS_DEBUG_USERS
	SELECT	MODULE,DEBUG,'UPLOAD'
	FROM	CSTBS_DEBUG_USERS
	WHERE	USER_ID = L_TMP;
	DELETE	CSTBS_DEBUG_USERS
	WHERE	USER_ID = L_TMP;
	
	IF L_IN_BG_RUNNING = 'Y'
	THEN
		--mspks_dist.pr_start_bg_in;
null;
	END IF;
END;
/
