SELECT COUNT(1), BATCH_NO,AC_BRANCH FROM ACTB_DAILY_lOG WHERE BATCH_NO > 8999 GROUP BY BATCH_NO,AC_BRANCH;
SELECT COUNT(1), BATCH_NO,BRANCH_CODE,UPLOAD_STAT FROM DETB_UPLOAD_DETAIL GROUP BY BATCH_NO,BRANCH_CODE,UPLOAD_STAT;
SELECT COUNT(1), BRANCH_DATE FROM DETB_DAILY_UPLOAD_EXCEPTIONS GROUP BY BRANCH_DATE;