UNDEF USER_ID
SET VERIFY OFF
set feed off
DELETE FROM CSTB_DEBUG_USERS WHERE USER_ID = (UPPER('&&USER_ID'))
/
INSERT INTO CSTB_DEBUG_USERS select module, 'Y', (UPPER('&&USER_ID'))
from cstb_debug
/
COMMIT
/
set feed on
PROMPT DEBUG IS SET ON FOR &&USER_ID
UNDEF USER_ID
SET VERIFY ON
