SELECT a.contract_ref_no, a.component, a.due_date,
s1,s2,p1,p2 FROM
(
SELECT SUM(AMOUNT_SETTLED) S1,
       SUM(NVL(PREPAID_AMT,0)) P1,
       COMPONENT,
       DUE_DATE,
       CONTRACT_REF_NO
FROM   CSTB_AMOUNT_PAID
WHERE  SUBSTR(CONTRACT_REF_NO,4,4) IN
        (SELECT PRODUCT_CODE FROM CSTM_PRODUCT
         WHERE MODULE = 'LD')
and payment_status <> 'V'
GROUP BY CONTRACT_REF_NO,DUE_DATE,COMPONENT
) A,
(
SELECT SUM(AMOUNT_SETTLED) S2,
       SUM(NVL(AMOUNT_PREPAID,0)) P2,
       COMPONENT,
       DUE_DATE,
       CONTRACT_REF_NO
FROM   CSTB_AMOUNT_DUE
WHERE  SUBSTR(CONTRACT_REF_NO,4,4) IN
        (SELECT PRODUCT_CODE FROM CSTM_PRODUCT
         WHERE MODULE = 'LD')
GROUP BY CONTRACT_REF_NO,DUE_DATE,COMPONENT
) B
WHERE A.CONTRACT_REF_NO = B.CONTRACT_REF_NO
AND   A.COMPONENT = B.COMPONENT
AND   A.DUE_DATE = B.DUE_DATE
and ((s1<>s2) or (p1<>p2))
/