DECLARE
B VARCHAR2(3) := '052';
/*





*/

D DATE := TO_DATE('01-AUG-2005','DD-MON-RRRR');
C NUMBER;
N NUMBER := 0;

TBC NUMBER := 0;
TDE NUMBER := 0;
TFT NUMBER := 0;
TFX NUMBER := 0;
TIC NUMBER := 0;
TLC NUMBER := 0;
TLD NUMBER := 0;
TRT NUMBER := 0;

FUNCTION FN (PM VARCHAR2) RETURN NUMBER
IS
X NUMBER;
BEGIN
SELECT CNT INTO X FROM VOL WHERE BR =B AND DT = D AND MODULE = PM;
RETURN X;
EXCEPTION WHEN OTHERS THEN RETURN 0;
END;

BEGIN
LOOP
	SELECT COUNT(1) INTO C FROM VOL WHERE BR = B AND DT = D;
	IF C > 0
	THEN
		N := N+1;
		TBC := TBC + FN('BC');
		TDE := TDE + FN('DE');
		TFT := TFT + FN('FT');
		TFX := TFX + FN('FX');
		TIC := TIC + FN('IC');
		TLC := TLC + FN('LC');
		TLD := TLD + FN('LD');
		TRT := TRT + FN('RT');
	END IF;
	D := D+1;
	IF D >= TO_DATE('01-SEP-2005','DD-MON-RRRR')
	THEN
		EXIT;
	END IF;
END LOOP;
INSERT INTO V1 (BR,BC,DE,FT,FX,IC,LC,LD,RT,T)
VALUES (B,TBC,TDE,TFT,TFX,TIC,TLC,TLD,TRT,N);
END;
/
