@storeset
SET SERVEROUT ON SIZE 1000000 VERIFY OFF
DECLARE
  TMP_NUMBER NUMBER := 0;
BEGIN
  IF GLOBAL.CURRENT_BRANCH IS NULL THEN GLOBAL.PR_INIT(GLOBAL.HEAD_OFFICE,'SYSTEM');END IF;
  IF NOT Cypks.fn_amt_round ('&CCY','&amount',tmp_number) THEN
  	DBMS_OUTPUT.PUT_LINE('FAILED ');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ROUNDED AMT IS '||tmp_number);
END;
/

@restoreset

