undef sid
@storeset
SET FEED OFF LINE 9999 PAGES 0 TRIMSPOOL ON VERIFY OFF
SPOOL TMP.TMP
SELECT
'SELECT * FROM '||object_name||' WHERE ROWID = DBMS_ROWID.ROWID_CREATE(1,'||ROW_WAIT_OBJ#||','||ROW_WAIT_FILE# ||','||ROW_WAIT_BLOCK#||','||ROW_WAIT_ROW#||  ');'
FROM V$SESSION A,
USER_OBJECTS B
WHERE A.ROW_WAIT_OBJ# = B.OBJECT_ID
AND SID = '&SID'
/
SPO OFF
@restoreset
@TMP.TMP


