SET FEED OFF VERIFY OFF
UNDEFINE ONAME
UNDEFINE SCHEMA
UNDEFINE DIR

SET SERVEROUT ON SIZE 10000
CL SCR
ACCEPT DIR CHAR PROMPT 'ENTER DIRECTORY   -> '
ACCEPT SCHEMA CHAR PROMPT 'ENTER SCHEMA NAME -> '
ACCEPT ONAME CHAR PROMPT 'ENTER OBJECT NAME -> '

HOST MD &&DIR

SPOOL TMP.CVR
DECLARE
	X VARCHAR2(1000) := UPPER('&&ONAME');
	Y VARCHAR2(1000);
	D VARCHAR2(1000) := '&&DIR';
	PROCEDURE P (T IN VARCHAR2) IS BEGIN DBMS_OUTPUT.PUT_LINE(T); END;
BEGIN
	IF SUBSTR(D,-1,1) NOT IN ('\','/')
	THEN
		IF INSTR(D,'\',1) > 0
		THEN
			D := D||'\';
		ELSE
			D := D||'/';
		END IF;
	END IF;

	SELECT	OBJECT_TYPE
	INTO	Y
	FROM	ALL_OBJECTS
	WHERE	OBJECT_NAME = X
	AND	OWNER = UPPER('&&SCHEMA')
	AND	ROWNUM = 1;

	IF Y IN ('FUNCTION','PROCEDURE')
	THEN
		IF Y = 'FUNCTION'
		THEN
			P('SPOOL '||D||X||'.FNC');
		ELSE
			P('SPOOL '||D||X||'.PRC');
		END IF;
		P('SET TRIMSPOOL ON LINE 9999 PAGES 0');
		P('PROMPT --- START DDL FOR '||Y||' &&ONAME');
		P('SELECT	DECODE(ROWNUM,1,''CREATE OR REPLACE ''||');
		P('SUBSTR(TEXT,1,INSTR(UPPER(TEXT),UPPER(''&&ONAME''))-1)||''&&SCHEMA''||''.''||''&&ONAME''||');
		P('SUBSTR(TEXT,INSTR(UPPER(TEXT),UPPER(''&&ONAME''))+ LENGTH(''&&ONAME'')),');
		P('TEXT) FROM	ALL_SOURCE');
		P('WHERE 	NAME = UPPER (''&&ONAME'') AND TYPE=UPPER('''||Y||''')');
		P('AND	OWNER = UPPER(''&&SCHEMA'')');
		P('ORDER BY LINE;');
		P('PROMPT /');
		P('PROMPT --- END OF DDL FOR '||Y||' &&ONAME');
		FOR DB IN (SELECT NAME FROM V$DATABASE) LOOP P('PROMPT --- GENERATED SOURCE OF OWNER &&SCHEMA@'||DB.NAME||' AT '||TO_CHAR(SYSDATE,'DD-MON-RRRR HH24:MI:SS')||' BY USER '||USER); END LOOP;
		P('SPOOL OFF');
	ELSIF Y = 'VIEW'
	THEN
		P('SPOOL '||D||X||'.VW');
		P('SET TRIMSPOOL ON LINE 9999 PAGES 0 LONG 9999');
		P('PROMPT --- START DDL FOR '||Y||' &&ONAME');
		P('PROMPT CREATE OR REPLACE VIEW &&SCHEMA'||'.'||X||' AS');
		P('SELECT TEXT FROM ALL_VIEWS WHERE VIEW_NAME = '||CHR(39)||X||CHR(39));
		P('AND OWNER = UPPER('||CHR(39)||'&&SCHEMA'||CHR(39)||');');
		P('PROMPT /');
		P('PROMPT --- END OF DDL FOR '||Y||' &&ONAME');
		FOR DB IN (SELECT NAME FROM V$DATABASE) LOOP P('PROMPT --- GENERATED SOURCE OF OWNER &&SCHEMA@'||DB.NAME||' AT '||TO_CHAR(SYSDATE,'DD-MON-RRRR HH24:MI:SS')||' BY USER '||USER); END LOOP;
		P('SPOOL OFF');
	ELSIF Y IN ('PACKAGE','PACKAGE BODY')
	THEN
		SELECT 'ACCEPT OTYPE CHAR PROMPT '||CHR(39)||'ENTER OBJECT_TYPE -> '||CHR(39)
		INTO	Y
		FROM	DUAL;
		P(Y);
		P('SPOOL TMP.TMP');
		P('SELECT ''SPOOL '||D||X||'''||DECODE('''||CHR(38)||CHR(38)||'OTYPE'',''PACKAGE'',''.SPC'',''.SQL'')');
		P('FROM DUAL;');
		P('SPOOL OFF');
		P('@TMP.TMP');
		P('SET TRIMSPOOL ON LINE 9999 PAGES 0');
		P('PROMPT --- START DDL FOR '||CHR(38)||CHR(38)||'OTYPE &&ONAME');
		P('SELECT	DECODE(ROWNUM,1,''CREATE OR REPLACE ''||');
		P('SUBSTR(TEXT,1,INSTR(UPPER(TEXT),UPPER(''&&ONAME''))-1)||''&&SCHEMA'||'.'||'&&ONAME''||');
		P('SUBSTR(TEXT,INSTR(UPPER(TEXT),UPPER(''&&ONAME''))+ LENGTH(''&&ONAME'')),');
		P('TEXT) FROM	ALL_SOURCE');
		P('WHERE 	NAME = UPPER (''&&ONAME'') AND TYPE=UPPER('''||CHR(38)||CHR(38)||'OTYPE'||''')');
		P('AND	OWNER = UPPER(''&&SCHEMA'')');
		P('ORDER BY LINE;');
		P('PROMPT /');
		P('PROMPT --- END OF DDL FOR '||CHR(38)||CHR(38)||'OTYPE &&ONAME');
		FOR DB IN (SELECT NAME FROM V$DATABASE) LOOP P('PROMPT --- GENERATED SOURCE OF OWNER &&SCHEMA@'||DB.NAME||' AT '||TO_CHAR(SYSDATE,'DD-MON-RRRR HH24:MI:SS')||' BY USER '||USER); END LOOP;
		P('SPOOL OFF');
	ELSE
		P('SET TRIMSPOOL ON LINE 9999 PAGES 0 LONG 9999');
		IF Y = 'TRIGGER'
		THEN
			P('SPOOL '||D||'TRG_BODY_'||X||'.BKP');
			P('SELECT TRIGGER_BODY FROM ALL_TRIGGERS WHERE OWNER = UPPER(''&&SCHEMA'') AND TRIGGER_NAME='||CHR(39)||X||CHR(39)||';');
			P('SPOOL OFF');
			P('SPOOL '||D||X||'.TRG');
			P('PROMPT --- ADD ";" OR "/" AFTER THE CREATE STMT IF ITS MISSING!');
		ELSE
			P('SPOOL '||D||X||'.DDL');
		END IF;
		P('PROMPT --- START DDL FOR '||Y||' &&ONAME');
		P('SELECT DBMS_METADATA.GET_DDL('||CHR(39)||Y||CHR(39)||','||CHR(39)||X||CHR(39)||',''&&SCHEMA'') FROM DUAL;');
		P('PROMPT /');
		P('PROMPT --- END OF DDL FOR '||Y||' &&ONAME');
		FOR DB IN (SELECT NAME FROM V$DATABASE) LOOP P('PROMPT --- GENERATED SOURCE OF OWNER &&SCHEMA@'||DB.NAME||' AT '||TO_CHAR(SYSDATE,'DD-MON-RRRR HH24:MI:SS')||' BY USER '||USER); END LOOP;
		P('SPOOL OFF');
	END IF;
EXCEPTION
	WHEN NO_DATA_FOUND
	THEN
		P('PROMPT INVALID OBJECT NAME '||X);
	WHEN OTHERS
	THEN
		P('ERROR OCCURED '||SQLERRM);
END;
/
SPOOL OFF
CL SCR
PROMPT ENTER DIRECTORY   -> &&DIR
PROMPT ENTER SCHEMA NAME -> &&SCHEMA
PROMPT ENTER OBJECT_NAME -> &&ONAME

@TMP.CVR
SET FEED ON PAGES 100

