SELECT FUNCTION_ID,TO_CHAR(SYSTEM_START_TIME,'DD-MON-YYYY HH24 : MI: SS'),USER_ID,TERMINAL_ID
,TO_CHAR(SYSTEM_END_TIME,'DD-MON-YYYY HH24 : MI: SS')FROM SMTB_SMS_LOG WHERE TO_CHAR(SYSTEM_START_TIME,'DD-MON-YYYY') IN ('28-MEI-2001')
ORDER BY  SYSTEM_START_TIME
/
