REM SOURCE.SQL START
SET FEED OFF
SET VERIFY OFF
UNDEFINE NAME
UNDEFINE TYPE
HOST MD C:\SOURCE

SET SERVEROUT ON SIZE 10000
SPOOL TEMP.CVR
DECLARE
X VARCHAR2(1000) := '&&NAME';
Y VARCHAR2(1000) := '&&TYPE';
BEGIN
if Y='PACKAGE BODY' then
DBMS_OUTPUT.PUT_LINE('SPOOL C:\SOURCE\'||X||'.SQL');
elsif Y='PACKAGE' then
DBMS_OUTPUT.PUT_LINE('SPOOL C:\SOURCE\'||X||'.SPC');
elsif Y='PROCEDURE' then
DBMS_OUTPUT.PUT_LINE('SPOOL C:\SOURCE\'||X||'.PRC');
elsif Y='FUNCTION' then
DBMS_OUTPUT.PUT_LINE('SPOOL C:\SOURCE\'||X||'.FNC');
elsif Y='TRIGGER' then
DBMS_OUTPUT.PUT_LINE('SPOOL C:\SOURCE\'||X||'.TRG');
end if;
END;
/
SPOOL OFF
@temp.cvr
SET TRIMSPOOL ON
SET LINE 999
SET PAGES 0
SELECT DECODE
(SUBSTR(UPPER(TEXT),1,LENGTH (TYPE||' '||UPPER('&&NAME'))),TYPE||' '||UPPER('&&NAME'),DECODE(TYPE,'PACKAGE BODY','/
---- END OF PACKAGE SPEC &&NAME
--','--')||'-- START OF DDL SCRIPT FOR &&NAME
---- '||TYPE||'
CREATE OR REPLACE '||TEXT,TEXT)
FROM ALL_SOURCE WHERE NAME = UPPER ('&&NAME') and Type=upper('&&TYPE')
AND owner = 'FLXT';
PROMPT /
PROMPT ---- END OF DDL FOR &&NAME
select '---- GENERATED AT '||to_char(sysDATE,'DD-MON-YYYY HH24:MI:SS') systime FROM DUAL;
SPOOL OFF

SPOOL TEMP.CVR
DECLARE
X VARCHAR2(1000) := '&&NAME';
Y VARCHAR2(1000) := '&&TYPE';
BEGIN
if Y='PACKAGE BODY' then
DBMS_OUTPUT.PUT_LINE('HOST NOTEPAD C:\SOURCE\'||X||'.SQL');
elsif Y='PACKAGE' then
DBMS_OUTPUT.PUT_LINE('HOST NOTEPAD C:\SOURCE\'||X||'.SPC');
elsif Y='PROCEDURE' then
DBMS_OUTPUT.PUT_LINE('HOST NOTEPAD C:\SOURCE\'||X||'.PRC');
elsif Y='FUNCTION' then
DBMS_OUTPUT.PUT_LINE('HOST NOTEPAD C:\SOURCE\'||X||'.FNC');
elsif Y='TRIGGER' then
DBMS_OUTPUT.PUT_LINE('HOST NOTEPAD C:\SOURCE\'||X||'.TRG');
END IF;
END;
/
SPOOL OFF
@temp.cvr
SET FEED ON
SET VERIFY ON
UNDEFINE NAME
