SET HEAD OFF
SET TRIMSPOOL ON
SPO COMPILE.SQL
SELECT 'ALTER '|| DECODE(OBJECT_TYPE,'PACKAGE BODY','PACKAGE',OBJECT_TYPE)
||' '||OBJECT_NAME||' COMPILE ' || DECODE(OBJECT_TYPE,'PACKAGE BODY','BODY') || ';'
FROM USER_OBJECTS
WHERE STATUS='INVALID' ORDER BY CREATED;

SPO OFF

SET HEAD ON

SELECT COUNT(1), OBJECT_TYPE
FROM USER_OBJECTS
WHERE STATUS = 'INVALID'
GROUP BY OBJECT_TYPE
/
