SET TRIMSPOOL ON PAGES 0 LINE 999 FEED OFF
SPOOL #$%.CVR
SELECT 'SELECT '||CHR(39)||'TRUNCATE TABLE '||TABLE_NAME||';'||CHR(39)||' FROM '||TABLE_NAME||' HAVING COUNT(1) > 0;'
FROM USER_TABLES
/
SPOOL OFF
SPOOL #$%1.CVR
@#$%.CVR
SPOOL OFF
SET FEED ON
