 SELECT UNITHOLDERID ,
    (SELECT SUM(SUM(UnitsIn-UnitsOut)*B.PRICE) HOLDINGS
    FROM UHBalLedgerTbl A, SUCCESSIONPRICETBL B
    WHERE
    A.FUNDID = B.FUNDID
    AND A.UnitholderID = '44140' AND
    TransactionDate <= '31-DEC-2001'
    GROUP BY B.FUNDID,B.PRICE FROM UNITHOLDERTBL) HOLDINGSVALUE
 FROM UNITHOLDERTBL WHERE UNITHOLDERID = '44140'
/
