UPDATE STTM_BRANCH SET HOST_NAME = '&&HOST_NAME'
/
UPDATE STTM_CUSTOMER SET LIAB_NODE = '&&HOST_NAME'
/
UPDATE LMTB_OFFLINE_NODES SET NODE_NAME = '&&HOST_NAME'
/
UPDATE ICTB_ACC_ACTION SET NODE = '&&HOST_NAME'
/
UPDATE ICTB_ACTION_LOG SET NODE = '&&HOST_NAME'
/
UPDATE LMTB_OFFLINE_UTILS SET NODE_NAME = '&&HOST_NAME'
/
UPDATE MSTB_COMMSG_MASTER SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_CURRENT_MSG_IND_OUT SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_IN SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_IN_HIST SET NODE = '&&HOST_NAME'
/
UPDATE MSTB_DLY_MSG_OUT SET NODE  = '&&HOST_NAME'
/
UPDATE MSTM_MCS SET NODE = '&&HOST_NAME'
/
UPDATE MSTM_UNDO set node = '&&HOST_NAME'
/
UPDATE STTM_UPLOAD_CUSTOMER SET LIAB_NODE = '&&HOST_NAME'
/
UPDATE CSTB_PARAM SET PARAM_VAL = '&WORK_AREA' WHERE PARAM_NAME = 'WORK_AREA'
/
UPDATE CSTB_PARAM SET PARAM_VAL = '&HANDOFF_AREA' WHERE PARAM_NAME = 'HANDOFF_AREA'
/
