UPDATE STTM_CUSTOMER SET LIAB_NODE = 'FCLAU.WORLD'
/
UPDATE LMTB_OFFLINE_NODES SET NODE_NAME = 'FCLAU.WORLD'
/
UPDATE ICTB_ACC_ACTION SET NODE = 'FCLAU.WORLD'
/
UPDATE ICTB_ACTION_LOG SET NODE = 'FCLAU.WORLD'
/
UPDATE LMTB_OFFLINE_UTILS SET NODE_NAME = 'FCLAU.WORLD'
/
UPDATE MSTB_COMMSG_MASTER SET NODE = 'FCLAU.WORLD'
/
UPDATE MSTB_CURRENT_MSG_IND_OUT SET NODE = 'FCLAU.WORLD'
/
UPDATE MSTB_DLY_MSG_IN SET NODE = 'FCLAU.WORLD'
/
UPDATE MSTB_DLY_MSG_IN_HIST SET NODE = 'FCLAU.WORLD'
/
UPDATE MSTB_DLY_MSG_OUT SET NODE  = 'FCLAU.WORLD'
/
UPDATE MSTM_MCS SET NODE = 'FCLAU.WORLD'
/
UPDATE MSTM_UNDO set node = 'FCLAU.WORLD'
/
UPDATE STTM_UPLOAD_CUSTOMER SET LIAB_NODE = 'FCLAU.WORLD'
/
