CREATE TABLE TMP1 AS SELECT *FROM SMVW_BROWSER_FUNCTIONS

SELECT * FROM TMP1
ALTER TABLE TMP1 ADD CONTROL_STRING VARCHAR2(100)
declare
x varchar2(100);
begin
for i in (select a.*,a.rowid rid from tmp1 a order by branch_code) loop
if nvl(global.current_branch,'XXX') <> i.branch_code then
global.pr_init(i.branch_code,'SYSTEM');
end if;
x := NULL;
x := smpkss.fn_get_controlstrings(i.user_id, i.function_id ,'','','');
update tmp1 set control_string = x
where rowid = i.rid;
end loop;
end;


UPDATE tmp1
SET CONTROL_STRING = SUBSTR(CONTROL_STRING,1,8)||'00000000'
WHERE function_id IN (SELECT FUNCTION_ID FROM
SMTB_MENU WHERE TYPE_STRING ='M')

UPDATE tmp1
SET CONTROL_STRING = '0000000000000000'
WHERE function_id IN (SELECT FUNCTION_ID FROM
SMTB_MENU WHERE TYPE_STRING ='B')

UPDATE tmp1
SET CONTROL_STRING = SUBSTR(CONTROL_STRING,1,14)||'00'
WHERE function_id IN (SELECT FUNCTION_ID FROM
SMTB_MENU WHERE TYPE_STRING ='O')


SELECT USER_ID,FUNCTION_ID,LANG_CODE,MAIN_MENU,SUB_MENU_1,TYPE_STRING,''''||BRANCH_CODE,
DECODE( SUBSTR(CONTROL_STRING,1,1),1,'Y','N') NEW_,
DECODE( SUBSTR(CONTROL_STRING,2,1),1,'Y','N')  COPY_,
DECODE( SUBSTR(CONTROL_STRING,3,1),1,'Y','N')  DELETE_,
DECODE( SUBSTR(CONTROL_STRING,4,1),1,'Y','N')  CLOSE_,
DECODE( SUBSTR(CONTROL_STRING,5,1),1,'Y','N')  UNLOCK_,
DECODE( SUBSTR(CONTROL_STRING,6,1),1,'Y','N')  REOPEN_,
DECODE( SUBSTR(CONTROL_STRING,7,1),1,'Y','N')  PRINT_,
DECODE( SUBSTR(CONTROL_STRING,8,1),1,'Y','N')  AUTH_,
DECODE( SUBSTR(CONTROL_STRING,9,1),1,'Y','N')  REVERSE_,
DECODE( SUBSTR(CONTROL_STRING,10,1),1,'Y','N')  ROLLOVER_,
DECODE( SUBSTR(CONTROL_STRING,11,1),1,'Y','N')  CONFIRM_,
DECODE( SUBSTR(CONTROL_STRING,12,1),1,'Y','N')  LIQUIDATE_,
DECODE( SUBSTR(CONTROL_STRING,13,1),1,'Y','N')  HOLD_,
DECODE( SUBSTR(CONTROL_STRING,14,1),1,'Y','N')  TEMPLATE_,
DECODE( SUBSTR(CONTROL_STRING,15,1),1,'Y','N')  VIEW_,
DECODE( SUBSTR(CONTROL_STRING,16,1),1,'Y','N')  GENRATE_
FROM TMP1 A



SELECT *FROM SMTB_USER ORDER BY 2

SELECT USER_ID,ROLE_ID,AUTH_STAT,BRANCH_CODE FROM SMTB_USER_ROLE
ORDER BY 1,4