INSERT INTO smtb_user
(EXIT_FUNCTION,USER_ID,START_DATE,USER_NAME,USER_PASSWORD,STATUS_CHANGED_ON,TILL_ALLOWED,ACCLASS_ALLOWED, 
PRODUCTS_ALLOWED,BRANCHES_ALLOWED,LAST_SIGNED_ON,MAX_OVERRIDE_AMT,TIME_LEVEL,USER_CATEGORY,USER_STATUS, 
END_DATE,PWD_CHANGED_ON,MAX_TXN_AMT,MAX_AUTH_AMT,NO_CUMULATIVE_LOGINS,NO_SUCCESSIVE_LOGINS,FORCE_PASSWD_CHANGE, 
USER_LANGUAGE,STARTUP_FUNCTION,HOME_BRANCH,FWDREW_COUNT,GL_ALLOWED,AUTH_STAT,CHECKER_DT_STAMP,CHECKER_ID, 
MAKER_DT_STAMP,MAKER_ID,MOD_NO,ONCE_AUTH,RECORD_STAT,USER_PASSWORD_BRN,USER_ID_BRN,USER_TXN_LIMIT,LIMITS_CCY, 
AUTO_AUTH,PROPAGATE_TO_WORKFLOW,CUSTOMER_NO,PRODUCTS_ACCESS_ALLOWED)
VALUES 
('','PRIYANKA','28-DEC-2006','1Z4b6d8V1C2b2E2C0F1b2C3d','1Z5A7C9E1C2b2E2C0F1V3A4V','24-SEP-2009','D',
'D','D','D','03-SEP-2008',0,9,'S','E','29-DEC-2060','01-JUL-2008',0,0,8,0,0,'ENG','','100',NULL,
'D','A','03-SEP-2008','PRIYANKA','03-SEP-2008','PRIYANKA',10,'Y','O','','','N','','Y','','','D')
/
