INSERT INTO smtb_user_role
(ROLE_ID,USER_ID,AUTH_STAT,BRANCH_CODE)
VALUES 
('ALLROLES','PRIYANKA','A','100')
/
INSERT INTO smtb_user_role
(ROLE_ID,USER_ID,AUTH_STAT,BRANCH_CODE)
VALUES 
('ALLROLES','PRIYANKA','A','130')
/
INSERT INTO smtb_user_role
(ROLE_ID,USER_ID,AUTH_STAT,BRANCH_CODE)
VALUES 
('ALLROLES','PRIYANKA','A','150')
/
INSERT INTO smtb_user_role
(ROLE_ID,USER_ID,AUTH_STAT,BRANCH_CODE)
VALUES 
('ALLROLES','PRIYANKA','A','160')
/
