INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','FORMS60_PATH','g:\flexcube\tempsoft\fmx;g:\flexcube\fmx','O','A',1,'PRIYANKA',
'04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','HELP_PATH','http://prodapp:7777/fchelp','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM',
'04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','NLS_DATE_FORMAT','DD-MON-RRRR','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005',
'Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','REPORTS60_PATH','g:\flexcube\rep','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM',
'04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','REPORTS_SPOOL_PATH','G:\SPOOL','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005',
'Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','DEBUGMODE','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','DISPLAY','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','GRAPHICS60_PATH','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','HELPMODE','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','HINTREQUIRED','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','IMPLI_TYPE','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','LANG','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','SERVER_REPORTS','','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','TERMINALID','T481','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
INSERT INTO smtb_user_reg
(USER_ID,PARAM_NAME,PARAM_VALUE,RECORD_STAT,AUTH_STAT,MOD_NO,MAKER_ID,MAKER_DT_STAMP,CHECKER_ID,CHECKER_DT_STAMP, 
ONCE_AUTH)
VALUES 
('PRIYANKA','TITLE_BAR_TEXT','IVBLIVE5','O','A',1,'PRIYANKA','04-NOV-2005','SYSTEM','04-NOV-2005','Y')
/
