UNDEFINE ACCOUNT
DECLARE
	L_BAL		NUMBER;
	L_LCY_BAL	NUMBER;
	L_DR_TUR	NUMBER;
	L_CR_TUR	NUMBER;
	CURSOR C IS
		SELECT	DISTINCT VALUE_DT, AC_BRANCH, AC_CCY, AC_NO
		FROM	ACVW_ALL_AC_ENTRIES
		WHERE	AC_NO = '&&ACCOUNT'
		ORDER BY 1;
BEGIN
	DELETE VDBAL$ WHERE ACC = '&&ACCOUNT';
	FOR X IN C
	LOOP
		SELECT	SUM(DECODE(DRCR_IND,'D',-1,1)*LCY_AMOUNT),
			SUM(DECODE(DRCR_IND,'D',-1,1)*FCY_AMOUNT)
		INTO	L_LCY_BAL,
			L_BAL
		FROM	ACVW_ALL_AC_ENTRIES
		WHERE	AC_NO = X.AC_NO
		AND	VALUE_DT <= X.VALUE_DT;
		SELECT	SUM(DECODE(DRCR_IND,'D',1,0)*NVL(FCY_AMOUNT,LCY_AMOUNT)),
			SUM(DECODE(DRCR_IND,'C',1,0)*NVL(FCY_AMOUNT,LCY_AMOUNT))
		INTO	L_DR_TUR,
			L_CR_TUR
		FROM	ACVW_ALL_AC_ENTRIES
		WHERE	AC_NO = X.AC_NO
		AND	VALUE_DT = X.VALUE_DT;
		INSERT INTO VDBAL$
			(
			BRN,
			ACC,
			VAL_DT,
			BAL,
			DR_TUR,
			CR_TUR,
			CCY,
			LCY_BAL
			)
		VALUES
			(
			X.AC_BRANCH,
			X.AC_NO,
			X.VALUE_DT,
			L_BAL,
			L_DR_TUR,
			L_CR_TUR,
			X.AC_CCY,
			L_LCY_BAL
			);
	END LOOP;
	UPDATE	VDBAL$
	SET	BAL = LCY_BAL
	WHERE	CCY = 'EUR'
	AND	ACC = '&&ACCOUNT';
END;
/
UNDEFINE ACCOUNT
